const CONTACT_EMAIL = "info@ebrostay.com";
const WHATSAPP_NUMBER = "34678715418";

const translations = {
  es: {
    "meta.title": "Ebrostay | Alquiler corporativo de media estancia en Zaragoza",
    "meta.description": "Ebrostay gestiona viviendas amuebladas de media estancia en Zaragoza para empresas y profesionales, y la gestión integral para propietarios. El puente entre ambos.",
    "nav.search": "Buscar",
    "nav.how": "Cómo funciona",
    "nav.owners": "Propietarios",
    "nav.contact": "Contacto",
    "nav.cta": "Buscar vivienda",
    "hero.imageAlt": "Apartamento amueblado en Zaragoza",
    "hero.kicker": "Alojamiento corporativo de media estancia, 100% digital",
    "hero.title": "Reserva tu hogar en Zaragoza en minutos.",
    "hero.copy": "Viviendas amuebladas y verificadas para estancias de 1 a 12 meses, pensadas para equipos y profesionales desplazados. Precio total transparente, reserva y pago online, un único contacto de principio a fin.",
    "hero.trust1": "Viviendas verificadas",
    "hero.trust2": "Precio total sin sorpresas",
    "hero.trust3": "Reserva y pago online",
    "search.city": "Ciudad",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Entrada",
    "search.moveOut": "Salida",
    "search.guests": "Personas",
    "search.button": "Buscar",
    "market.kicker": "Búsqueda",
    "market.title": "Viviendas disponibles en Zaragoza",
    "filters.city": "Ciudad",
    "filters.checkIn": "Entrada",
    "filters.checkOut": "Salida",
    "filters.guests": "Personas",
    "filters.type": "Tipo de vivienda",
    "filters.typeAll": "Todos",
    "filters.typeApartment": "Apartamento",
    "filters.typeRoom": "Habitación",
    "filters.typeHome": "Casa",
    "filters.budget": "Presupuesto mensual máximo",
    "filters.anyBudget": "Sin límite",
    "filters.mustHave": "Imprescindible",
    "filters.sort": "Ordenar",
    "filters.sortBest": "Mejor opción",
    "filters.sortPrice": "Precio más bajo",
    "filters.sortNew": "Novedades",
    "filters.apply": "Aplicar filtros",
    "filters.reset": "Reiniciar",
    "filters.show": "Filtros",
    "quick.verified": "Verificadas",
    "quick.bills": "Gastos incluidos",
    "quick.deposit": "Fianza reembolsable",
    "status.all": "Mostrando {count} viviendas gestionadas.",
    "status.matches": "{count} viviendas encontradas.",
    "status.one": "1 vivienda encontrada.",
    "status.none": "No hay viviendas para esos filtros.",
    "status.invalid": "La fecha de salida debe ser posterior a la entrada.",
    "listing.available": "Disponible",
    "listing.unavailable": "No disponible",
    "listing.capacity": "Hasta {guests} personas",
    "listing.price": "{price}/mes",
    "listing.from": "Disponible desde {date}",
    "listing.rating": "{rating} valoración",
    "listing.view": "Ver vivienda",
    "listing.map": "Mapa",
    "listing.favorite": "Guardar",
    "listing.saved": "Guardado",
    "listing.request": "Solicitar",
    "listing.book": "Reservar",
    "badge.checked": "Verificada",
    "badge.deposit": "Fianza reembolsable",
    "badge.bills": "Gastos incluidos",
    "type.apartment": "Apartamento",
    "type.room": "Habitación",
    "type.home": "Casa",
    "amenity.wifi": "wifi",
    "amenity.desk": "mesa de trabajo",
    "amenity.balcony": "balcón",
    "amenity.lift": "ascensor",
    "amenity.ac": "aire acondicionado",
    "amenity.heating": "calefacción",
    "amenity.kitchen": "cocina equipada",
    "amenity.terrace": "terraza",
    "amenity.washer": "lavadora",
    "amenity.dishwasher": "lavavajillas",
    "amenity.tv": "TV",
    "amenity.microwave": "microondas",
    "amenity.oven": "horno",
    "amenity.parking": "parking",
    "spec.bedroom": "1 habitación",
    "spec.bedrooms": "{count} habitaciones",
    "spec.bathroom": "1 baño",
    "spec.bathrooms": "{count} baños",
    "spec.size": "{size} m²",
    "spec.floor": "Planta {floor}",
    "spec.groundFloor": "Planta baja",
    "detail.conditions": "Condiciones",
    "detail.video": "Ver vídeo de la vivienda",
    "cond.minStay": "Estancia mínima",
    "cond.maxStay": "Estancia máxima",
    "cond.month": "1 mes",
    "cond.months": "{count} meses",
    "cond.deposit": "Fianza",
    "cond.upfront": "Renta por adelantado",
    "movein.title": "Coste de entrada",
    "movein.upfront": "Renta por adelantado",
    "movein.deposit": "Fianza",
    "movein.total": "Total para entrar",
    "cond.eur": "{amount} EUR",
    "cond.utilities": "Límite de suministros",
    "cond.eurMonth": "{amount} EUR/mes",
    "cond.energy": "Certificado energético",
    "cond.beds": "Camas",
    "cond.pets": "Mascotas",
    "cond.smoking": "Se permite fumar",
    "cond.couples": "Parejas",
    "cond.selfCheckin": "Autoentrada con lockbox",
    "common.yes": "Sí",
    "common.no": "No",
    "cal.legend": "Los días tachados en rojo no están disponibles.",
    "nav.about": "Nosotros",
    "about.kicker": "Sobre Ebrostay",
    "about.title": "El puente entre empresas y propietarios.",
    "about.lead": "Ebrostay reconstruye la gestión del alquiler de media estancia desde primeros principios: servicio de primer nivel para las empresas que alojan a su gente y para los propietarios que nos confían su vivienda. Con raíces en Zaragoza, pensado para Europa.",
    "about.mvKicker": "Misión y visión",
    "about.mvTitle": "A dónde vamos y qué hacemos cada día.",
    "about.visionLabel": "Nuestra visión",
    "about.visionCopy": "Convertirnos en la empresa de gestión de propiedades número uno de Europa en alquiler corporativo de media estancia: primero en Zaragoza y, después, ciudad a ciudad por todo el continente.",
    "about.missionLabel": "Nuestra misión",
    "about.missionCopy": "Ser el puente entre empresas y propietarios, con un servicio de primer nivel para ambos lados: una vivienda que simplemente funciona para el inquilino y rentabilidad sin complicaciones para el propietario.",
    "about.bridgeKicker": "El puente",
    "about.bridgeTitle": "Un puente, en todos los sentidos.",
    "about.bridgeLead": "Nuestro logo es un puente, y encierra dos significados. El primero es puro Zaragoza: los puentes que cruzan el Ebro —el río que da nombre a Ebrostay—, como el emblemático Puente de Piedra que une las dos orillas de la ciudad desde hace siglos.",
    "about.bridgeLead2": "El segundo es lo que hacemos cada día: a un lado, las empresas y las personas que trasladan; al otro, los propietarios y sus viviendas. Ebrostay es el puente entre ambos, y se ocupa de todo lo que hay en medio para que ninguno tenga que hacerlo.",
    "about.bizTag": "Para empresas y equipos",
    "about.bizTitle": "Alojamiento listo para los negocios.",
    "about.bizCopy": "Aloja a tu equipo en Zaragoza sin fricción. Un contacto, un precio mensual claro y un único proceso de principio a fin.",
    "about.biz1": "Viviendas verificadas y listas para entrar, de 1 a 12 meses",
    "about.biz2": "Contratos, facturación y gestión de IVA preparados para empresas",
    "about.biz3": "Piso completo o por habitaciones, con flexibilidad de inquilinos",
    "about.bizCta": "Buscar vivienda",
    "about.ownerTag": "Para propietarios",
    "about.ownerTitle": "Tu vivienda, en piloto automático.",
    "about.ownerCopy": "Gestión integral sin que muevas un dedo. Llenamos, verificamos, contratamos, cobramos y damos soporte; tú ves llegar los ingresos a tu cuenta.",
    "about.owner1": "Anuncios profesionales, precio dinámico y alcance multicanal",
    "about.owner2": "Verificación de inquilinos, contratos, cobros y fianza gestionados",
    "about.owner3": "Panel en tiempo real y pagos directos a tu cuenta",
    "about.ownerCta": "Publicar mi vivienda",
    "about.fpKicker": "Primeros principios",
    "about.fpTitle": "Reconstruimos la gestión de propiedades desde cero.",
    "about.fpLead": "La gestión tradicional funciona con llamadas, papeleo, visitas a ciegas y comisiones ocultas. Descompusimos cada sub-área hasta sus primeros principios y la reconstruimos como algo digital, transparente y rápido.",
    "about.fp1t": "Precio y transparencia",
    "about.fp1c": "Un precio mensual claro. Sin comisiones ocultas ni sorpresas al firmar.",
    "about.fp2t": "Contratos y cumplimiento",
    "about.fp2c": "Contrato de temporada correcto, fianza y registro: lo gestionamos nosotros.",
    "about.fp3t": "Cobros y fianza",
    "about.fp3c": "Pago online seguro, facturación automática y fianza gestionada.",
    "about.fp4t": "Soporte y check-in",
    "about.fp4c": "Autoentrada con lockbox y soporte 24/7 en español e inglés.",
    "about.rootsKicker": "Zaragoza → Europa",
    "about.ctaTitle": "Con raíces en Zaragoza. Pensado para Europa.",
    "about.ctaCopy": "Empezamos donde conocemos cada calle y cada trayecto, y luego llevamos el mismo método a la siguiente ciudad. Tanto si alojas a un equipo como si publicas tu vivienda, hablas con el mismo puente.",
    "about.ctaFind": "Buscar vivienda",
    "about.ctaList": "Publicar mi vivienda",
    "account.title": "Mi cuenta",
    "bookings.button": "Mi cuenta",
    "bookings.title": "Mis reservas",
    "bookings.copy": "Las estancias confirmadas con tu cuenta aparecen aquí.",
    "bookings.empty": "Todavía no tienes reservas asociadas a tu cuenta. Cuando confirmes una estancia con nosotros, aparecerá aquí.",
    "bookings.error": "No se pudieron cargar tus reservas. Inténtalo de nuevo.",
    "book.title": "Reserva online",
    "book.start": "Entrada",
    "book.end": "Salida",
    "book.months": "Duración",
    "book.rent": "Alquiler",
    "book.payNow": "Total a pagar ahora",
    "book.stay": "Estancia",
    "book.button": "Reservar y pagar",
    "book.note": "Pagas ahora la estancia completa, la comisión de gestión y la fianza. La fianza es reembolsable al finalizar la estancia.",
    "book.loginFirst": "Inicia sesión en la página principal para reservar.",
    "book.unavailable": "Esas fechas no están disponibles.",
    "book.notConfigured": "El pago online aún no está activado. Escríbenos por WhatsApp y confirmamos tu reserva.",
    "book.error": "No se pudo iniciar el pago. Inténtalo de nuevo.",
    "book.redirecting": "Abriendo el pago seguro de Stripe...",
    "book.confirmed": "¡Reserva confirmada! Te hemos enviado un correo con los detalles.",
    "book.cancelled": "Pago cancelado. Tu reserva no se ha realizado.",
    "bookings.paidLabel": "Pagado",
    "bookings.invoice": "Factura",
    "bookings.pdf": "PDF",
    "bookings.receipt": "Recibo",
    "bookings.assignedLabel": "Confirmada",
    "account.loading": "Cargando tu cuenta…",
    "account.signedOutTitle": "Inicia sesión para ver tus reservas.",
    "account.signedOutCopy": "Tus estancias pagadas y asignadas, con sus facturas y recibos, aparecen aquí cuando entras con tu cuenta.",
    "account.sessionTitle": "Sesión y cuenta",
    "account.deactivate": "Desactivar mi cuenta",
    "account.deactivateConfirm": "Tu cuenta se desactivará y no podrás volver a entrar. Conservamos tu historial de reservas. Pulsa otra vez para confirmar.",
    "account.deactivateError": "No se pudo desactivar la cuenta. Inténtalo de nuevo.",
    "account.delete": "Eliminar mi cuenta",
    "account.deleteConfirm": "¿Seguro? Es definitivo. Pulsa otra vez para eliminar.",
    "account.deleteError": "No se pudo eliminar la cuenta. Inténtalo de nuevo.",
    "account.close": "Cerrar",
    "book.minStay": "Estancia mínima: {count} meses",
    "book.loginCta": "Inicia sesión para reservar →",
    "nav.privacy": "Privacidad",
    "admin.addProperty": "Añadir vivienda",
    "admin.addPropertyName": "Nombre de la nueva vivienda:",
    "detail.floorplan": "Plano de la vivienda",
    "detail.floorplanCopy": "Distribución orientativa de la vivienda.",
    "detail.distancesNote": "Tiempos de trayecto aproximados desde la vivienda.",
    "landmark.pilar": "Plaza del Pilar (centro)",
    "landmark.delicias": "Estación Delicias (AVE)",
    "landmark.plaza": "PLAZA (Plataforma Logística)",
    "dist.walk": "A pie",
    "dist.transit": "Transporte público (estimado)",
    "dist.car": "En coche",
    "admin.floorplan": "Plano",
    "admin.makeFloorplan": "Marcar como plano",
    "admin.unmakeFloorplan": "Quitar de planos",
    "dist.placeholder": "Tu trabajo, una dirección, un lugar...",
    "dist.calc": "Calcular distancia",
    "dist.searching": "Buscando dirección…",
    "dist.notFound": "No encontramos esa dirección. Prueba con calle y número.",
    "admin.floorplans": "Planos de la vivienda",
    "admin.addFloorplans": "Añadir planos",
    "admin.noFloorplans": "Todavía no hay planos.",
    "admin.floorplansCopy": "Se muestran en su propia sección del anuncio, separados de las fotos.",
    "admin.guestInfo": "Información para inquilinos",
    "admin.guestInfoCopy": "Wifi, llaves y contacto de emergencia. Solo visible para huéspedes con reserva en esta vivienda.",
    "share.button": "Compartir",
    "share.copied": "Enlace copiado al portapapeles",
    "share.text": "Mira esta vivienda en Ebrostay",
    "nav.menu": "Menú",
    "hero.ownerCta": "¿Eres propietario? Gana sin mover un dedo →",
    "why.kicker": "Por qué Ebrostay",
    "why.title": "Lo que los neobancos hicieron con la banca, nosotros lo hacemos con el alquiler.",
    "why.lead": "Todo digital, todo transparente, automatizado de punta a punta. Reconstruimos cada parte del alquiler desde primeros principios: sin papeleo interminable, sin llamadas, sin comisiones ocultas. Reservar una vivienda debería ser tan fácil como abrir una cuenta en tu móvil.",
    "why.c1.title": "Reserva en minutos",
    "why.c1.copy": "Elige fechas, paga online y recibe tu confirmación y factura al instante. Cero esperas.",
    "why.c2.title": "Transparencia total",
    "why.c2.copy": "El precio que ves es el que pagas: renta, fianza y condiciones claras desde el primer clic.",
    "why.c3.title": "Automatizado de extremo a extremo",
    "why.c3.copy": "Contrato, cobro, fianza, check-in y soporte gestionados por software. Menos fricción, menos errores.",
    "why.c4.title": "Soporte humano, canales modernos",
    "why.c4.copy": "WhatsApp, email y tu panel personal, en español e inglés. Respuestas rápidas, de verdad.",
    "split.guestTag": "Para empresas e inquilinos",
    "split.guestTitle": "Múdate sin fricción",
    "split.guestCopy": "Encuentra, reserva y entra. Todo lo que un profesional o un equipo entero necesita para su estancia, en un solo sitio.",
    "split.g1": "Viviendas verificadas con fotos, planos y distancias reales",
    "split.g2": "Reserva y pago seguro online con fianza reembolsable",
    "split.g3": "Wifi, llaves y contacto de emergencia en tu panel",
    "split.guestCta": "Buscar vivienda",
    "split.ownerTag": "Para propietarios",
    "split.ownerTitle": "Gana sin mover un dedo",
    "split.ownerCopy": "Gestión integral, sin involucración. Nosotros llenamos, cobramos y te transferimos. Tú recibes el dinero.",
    "split.o1": "Anuncios, fotos, precios y canales gestionados por nosotros",
    "split.o2": "Verificación de inquilinos, contratos, cobros y fianza",
    "split.o3": "Tu panel con ingresos en tiempo real y pagos a tu cuenta",
    "split.ownerCta": "Descubre la gestión sin esfuerzo",
    "owners.metaTitle": "Ebrostay | Gestión de alquiler sin esfuerzo para propietarios",
    "owners.metaDesc": "Ebrostay gestiona tu vivienda de media estancia de principio a fin: anuncios, inquilinos, cobros, fianza y pagos a tu cuenta. Tú no mueves un dedo.",
    "owners.portal": "Portal propietarios",
    "owners.cta": "Quiero unirme",
    "owners.kicker": "Gestión de alquiler · Zero touch",
    "owners.heroTitle": "Tu vivienda, en piloto automático. Tú solo recibes el dinero.",
    "owners.heroLead": "Ebrostay es la gestión de media estancia de nueva generación: digital, transparente y sin que muevas un dedo. Somos el puente hacia la demanda corporativa: nos ocupamos de todo el ciclo —del anuncio al pago en tu cuenta— mientras tú ves los ingresos crecer desde tu panel.",
    "owners.seeHow": "Ver cómo funciona",
    "owners.stat1n": "0",
    "owners.stat1l": "horas de gestión para ti",
    "owners.stat2n": "1–12",
    "owners.stat2l": "meses por estancia",
    "owners.stat3n": "100%",
    "owners.stat3l": "digital y transparente",
    "owners.compareKicker": "La diferencia",
    "owners.compareTitle": "Gestión tradicional vs. Ebrostay",
    "owners.compareCol0": " ",
    "owners.compareCol1": "Por tu cuenta / agencia clásica",
    "owners.cf1": "Anuncios, fotos y precio",
    "owners.ct1": "Lo haces tú, fotos con el móvil",
    "owners.ce1": "Profesional y optimizado por nosotros",
    "owners.cf2": "Búsqueda de inquilinos",
    "owners.ct2": "Llamadas, visitas, semanas vacías",
    "owners.ce2": "Pipeline activo y multicanal",
    "owners.cf3": "Verificación y contratos",
    "owners.ct3": "Papeleo manual, riesgo legal",
    "owners.ce3": "Verificación + contrato de temporada correcto",
    "owners.cf4": "Cobros y fianza",
    "owners.ct4": "Transferencias y recordatorios a mano",
    "owners.ce4": "Cobro online automático y fianza gestionada",
    "owners.cf5": "Entrada, limpieza e incidencias",
    "owners.ct5": "Tu teléfono suena a cualquier hora",
    "owners.ce5": "Check-in, turnover y soporte gestionados",
    "owners.cf6": "Tu visibilidad",
    "owners.ct6": "Excel y suposiciones",
    "owners.ce6": "Panel con ingresos y reservas en tiempo real",
    "owners.cf7": "Tu esfuerzo",
    "owners.ct7": "Alto y constante",
    "owners.ce7": "Cero",
    "owners.featKicker": "Gestión integral",
    "owners.featTitle": "Todo lo que hacemos por ti",
    "owners.f1t": "Anuncio profesional",
    "owners.f1c": "Fotos, textos en dos idiomas, planos y descripción optimizada.",
    "owners.f2t": "Precio dinámico",
    "owners.f2c": "Tarifas ajustadas a la demanda para maximizar tu ocupación.",
    "owners.f3t": "Distribución multicanal",
    "owners.f3c": "Tu vivienda visible donde buscan los inquilinos de media estancia.",
    "owners.f4t": "Verificación de inquilinos",
    "owners.f4c": "Filtramos y validamos a cada huésped antes de confirmar.",
    "owners.f5t": "Contratos y cumplimiento",
    "owners.f5c": "Contrato de temporada correcto, fianza y registro según la ley.",
    "owners.f6t": "Cobros y fianza",
    "owners.f6c": "Pago online seguro, gestión de fianza y facturación automática.",
    "owners.f7t": "Check-in y llaves",
    "owners.f7c": "Entrada coordinada y autoentrada cuando aplica.",
    "owners.f8t": "Limpieza y turnover",
    "owners.f8c": "Preparación entre estancias para mantener tu vivienda impecable.",
    "owners.f9t": "Soporte e incidencias",
    "owners.f9c": "Atendemos al inquilino para que tu teléfono no suene.",
    "owners.f10t": "Pagos a tu cuenta",
    "owners.f10c": "Transferimos tus ingresos a tu IBAN tras cada reserva, con detalle claro.",
    "owners.howKicker": "En 3 pasos",
    "owners.howTitle": "Empezar es así de fácil",
    "owners.h1t": "Cuéntanos tu vivienda",
    "owners.h1c": "Rellena el formulario. Evaluamos tu piso y te proponemos condiciones, sin compromiso.",
    "owners.h2t": "La preparamos y publicamos",
    "owners.h2c": "Fotos, textos, precio y canales. La activamos en cuanto está lista.",
    "owners.h3t": "Cobras desde tu panel",
    "owners.h3c": "Añades tu IBAN una vez y recibes tus ingresos tras cada estancia. Cero gestión.",
    "owners.applyKicker": "Únete",
    "owners.applyTitle": "Pon tu vivienda a trabajar",
    "owners.applyCopy": "Déjanos tus datos y un miembro del equipo te contacta en menos de 24 h con una propuesta a medida. Sin compromiso.",
    "owners.haveAccount": "¿Ya colaboras con nosotros? Entra en tu portal →",
    "owners.phone": "Teléfono",
    "owners.units": "¿Cuántas viviendas?",
    "owners.address": "Zona o dirección",
    "owners.msgPlaceholder": "Cuéntanos sobre tu vivienda...",
    "owners.submit": "Enviar solicitud",
    "owners.note": "Te contactamos en menos de 24 h. Sin compromiso.",
    "owners.sent": "¡Recibido! Te contactamos en menos de 24 h.",
    "owners.sentFallback": "Escríbenos a info@ebrostay.com y te respondemos enseguida.",
    "owners.aboutLink": "Ventajas",
    "partner.kicker": "Portal de propietarios",
    "partner.title": "Tu cartera, en tiempo real.",
    "partner.signinCopy": "Inicia sesión con la cuenta de propietario que te facilitamos para ver tus viviendas, ingresos y datos de pago.",
    "partner.notOwner": "Tu cuenta aún no está activada como propietario. Si quieres que gestionemos tu vivienda, envíanos una solicitud y la activamos.",
    "partner.metricProps": "Viviendas",
    "partner.metricBookings": "Reservas",
    "partner.metricRevenue": "Ingresos de reservas (bruto)",
    "partner.metricPayout": "Datos de pago",
    "partner.propsTitle": "Tus viviendas",
    "partner.bookingsTitle": "Reservas recientes",
    "partner.payoutTitle": "Datos de pago (alternativa manual)",
    "partner.payoutCopy": "Si prefieres transferencia manual, deja aquí tu IBAN. Tus datos están cifrados y solo los ve Ebrostay. Transferimos tras cada estancia confirmada.",
    "partner.holder": "Titular de la cuenta",
    "partner.iban": "IBAN",
    "partner.bank": "Banco",
    "partner.taxId": "NIF / NIE",
    "partner.billing": "Dirección de facturación",
    "partner.notes": "Notas (opcional)",
    "partner.savePayout": "Guardar datos de pago",
    "partner.noProps": "Todavía no tienes viviendas asignadas.",
    "partner.thStatus": "Estado",
    "partner.pending": "Pendiente",
    "partner.noBookings": "Todavía no hay reservas.",
    "partner.payoutSaved": "Datos de pago guardados.",
    "admin.section.owner": "Propietario",
    "admin.field.ownerEmail": "Email del propietario",
    "admin.ownerHint": "El propietario verá esta vivienda, sus reservas e ingresos en su portal. Debe tener una cuenta registrada con ese email.",
    "admin.ownerNotFound": "No existe una cuenta con ese email. Pide al propietario que se registre primero.",
    "partner.connectTitle": "Pagos automáticos",
    "partner.connectCopy": "Conecta tu cuenta con Stripe para recibir tus rentas automáticamente tras cada reserva, sin esperas ni transferencias manuales.",
    "partner.connectChecking": "Comprobando estado…",
    "partner.connectActive": "✓ Pagos automáticos activados. Recibes tus rentas tras cada reserva.",
    "partner.connectPending": "Onboarding casi listo. Stripe está verificando tus datos.",
    "partner.connectIncomplete": "Onboarding sin terminar. Completa los pasos para activar los pagos.",
    "partner.connectNone": "Activa los pagos automáticos para cobrar sin esperas.",
    "partner.connectUnavailable": "Los pagos automáticos aún no están disponibles. Mientras tanto, usa los datos de pago manuales más abajo.",
    "partner.connectStart": "Activar pagos automáticos",
    "partner.connectContinue": "Continuar onboarding",
    "partner.connectRedirect": "Abriendo Stripe…",
    "book.commission": "Comisión y gestión (15%, IVA 21% incl.)",
    "book.commissionDiscount": "Descuento estancia larga (tope 1 mes)",
    "book.tenants": "Inquilinos (uno por línea)",
    "book.tenantsPlaceholder": "Nombre y apellidos de cada inquilino",
    "book.vatExempt": "✓ Con los inquilinos identificados, la renta está exenta de IVA.",
    "book.vatCompany": "💡 Añade el nombre de todos los inquilinos para que la renta quede exenta de IVA. A nombre de una empresa sin inquilinos nombrados se aplica un 21% de IVA que la empresa autoliquida (no lo cobramos nosotros).",
    "book.splitNote": "Máximo 11 meses por contrato. Para estancias más largas se firman dos contratos: reserva hasta 11 meses ahora y te ayudamos con la prórroga.",
    "book.minStayError": "La estancia no llega a la duración mínima de esta vivienda.",
    "book.rangeUnavailable": "Esas fechas incluyen días ya reservados. Elige un rango disponible.",
    "book.justTaken": "Lo sentimos, otro usuario acaba de reservar la vivienda en esas fechas. Elige otras fechas disponibles.",
    "bookings.viewDetails": "Ver detalles de tu estancia",
    "booking.back": "Volver a mis reservas",
    "booking.kicker": "Tu reserva",
    "booking.notFoundTitle": "No encontramos esta reserva.",
    "booking.notFoundCopy": "Inicia sesión con la cuenta que hizo la reserva y vuelve a intentarlo.",
    "booking.viewProperty": "Ver anuncio de la vivienda",
    "booking.guestInfoTitle": "Información para tu estancia",
    "booking.guestInfoPending": "Te enviaremos los detalles de entrada (wifi, llaves y contacto) antes de tu llegada.",
    "booking.guestInfoHelp": "¿Dudas? Escríbenos a",
    "booking.paidAmount": "Pagado",
    "booking.status": "Estado",
    "booking.reference": "Referencia",
    "guest.wifiName": "Red wifi",
    "guest.wifiPassword": "Contraseña wifi",
    "guest.keyPickup": "Recogida de llaves",
    "guest.checkinTime": "Hora de entrada",
    "guest.checkoutTime": "Hora de salida",
    "guest.emergencyPhone": "Teléfono de emergencia",
    "guest.notes": "Notas",
    "admin.tabProperties": "Propiedades",
    "admin.tabBookings": "Reservas",
    "admin.propListCopy": "Pulsa una vivienda para editar sus textos, fotos, dirección y disponibilidad.",
    "admin.editProperty": "Editar",
    "admin.confirmedBookings": "Reservas confirmadas",
    "admin.confirmedCopy": "Reservas pagadas a través de Stripe, con fecha de confirmación, datos del huésped y factura.",
    "admin.assignedStays": "Estancias asignadas",
    "admin.assignedCopy": "Estancias asignadas manualmente a un huésped desde el editor de cada vivienda.",
    "admin.noBookings": "Todavía no hay reservas.",
    "admin.backToPanel": "Volver al panel",
    "admin.th.confirmed": "Confirmada",
    "admin.th.property": "Vivienda",
    "admin.th.checkin": "Entrada",
    "admin.th.checkout": "Salida",
    "admin.th.months": "Meses",
    "admin.th.amount": "Importe",
    "admin.th.name": "Nombre",
    "admin.th.email": "Email",
    "admin.th.invoice": "Factura",
    "admin.field.addressFull": "Dirección (calle y número)",
    "admin.addressHint": "La dirección se muestra en el anuncio y en la factura; las coordenadas se calculan automáticamente al guardar.",
    "auth.or": "o",
    "auth.signupTitle": "Crea tu cuenta",
    "auth.signupCopy": "Crea tu cuenta para reservar online y gestionar tus estancias.",
    "auth.forgot": "¿Has olvidado tu contraseña?",
    "auth.resetTitle": "Restablecer contraseña",
    "auth.resetCopy": "Escribe tu email y te enviaremos un enlace para crear una nueva contraseña.",
    "auth.resetSend": "Enviar enlace",
    "auth.resetError": "No se pudo enviar el correo. Revisa el email e inténtalo de nuevo.",
    "auth.recoverTitle": "Elige una nueva contraseña",
    "auth.recoverCopy": "Escribe la nueva contraseña para tu cuenta.",
    "auth.recoverSave": "Guardar contraseña",
    "auth.recoverError": "No se pudo guardar la contraseña. Inténtalo de nuevo.",
    "auth.successEmailTitle": "Revisa tu correo",
    "auth.successConfirmCopy": "Hemos enviado un enlace de confirmación a {email}. Ábrelo para activar tu cuenta y después inicia sesión.",
    "auth.successResetCopy": "Hemos enviado un enlace a {email} para restablecer tu contraseña.",
    "auth.successRecoverTitle": "Contraseña actualizada",
    "auth.successRecoverCopy": "Ya puedes usar tu nueva contraseña.",
    "auth.google": "Continuar con Google",
    "auth.microsoft": "Continuar con Outlook",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "Universidad - Pedro II el Católico",
    "properties.pedro1.copy": "Piso amueblado en Pedro II el Católico 3, preparado para estancias de media duración en Zaragoza.",
    "properties.pedro1.details": "Primero izquierda en una ubicación urbana y bien comunicada, con cocina equipada, zona de trabajo y gestión local Ebrostay.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "Universidad - Pedro II el Católico",
    "properties.pedro2.copy": "Segundo izquierda en el mismo edificio, una opción práctica para profesionales, estudiantes o traslados temporales.",
    "properties.pedro2.details": "Vivienda amueblada con distribución funcional, wifi, calefacción y soporte local para llegada y estancia.",
    "properties.movera0.name": "Movera 7 - Segunda Planta",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Piso de 3 habitaciones privadas en Movera 7 (segunda planta), ideal para equipos de empresa, técnicos y estancias por proyecto.",
    "properties.movera0.details": "Tres dormitorios privados con salón, comedor y cocina equipada compartidos y baño completo. Gastos incluidos con suministros limitados a 50 EUR por habitación, autoentrada con lockbox y soporte 24/7. Piso completo o por habitaciones.",
    "properties.movera0.priceNote": "o 450 EUR/habitación",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Piso de 3 habitaciones privadas en Movera 7, ideal para equipos de empresa, técnicos y estancias por proyecto.",
    "properties.movera1.details": "Tres dormitorios privados con salón, comedor y cocina equipada compartidos, baño completo y terraza. Gastos incluidos con suministros limitados a 50 EUR por habitación, autoentrada con lockbox y soporte 24/7. Piso completo o por habitaciones.",
    "properties.movera1.priceNote": "o 450 EUR/habitación",
    "map.title": "Mapa de viviendas",
    "map.copy": "Cada pin muestra el precio mensual de una vivienda. Toca un pin para resaltar la vivienda o usa los botones para ir a cada dirección.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "Cómo funciona",
    "how.title": "Busca, reserva y llega con todo claro.",
    "how.step1.title": "Filtra",
    "how.step1.copy": "Elige fechas, presupuesto, capacidad y comodidades para reducir la búsqueda.",
    "how.step2.title": "Revisa",
    "how.step2.copy": "Compara viviendas verificadas, detalles, ubicación, precio mensual y disponibilidad.",
    "how.step3.title": "Reserva",
    "how.step3.copy": "Reserva y paga online de forma segura: la estancia completa más la fianza reembolsable. Confirmación y factura al momento.",
    "owners.kicker": "Para propietarios",
    "owners.title": "Publica y opera tu vivienda con ayuda local.",
    "owners.copy": "Ebrostay prepara anuncios, coordina entradas, limpiezas, incidencias y comunicación con huéspedes para que tu propiedad funcione mejor sin absorber tu día.",
    "contact.kicker": "Contacto",
    "contact.title": "Cuéntanos qué necesitas.",
    "contact.copy": "Cuéntanos fechas, personas y presupuesto, o pide la gestión de tu vivienda. Te respondemos lo antes posible.",
    "contact.whatsapp": "Escríbenos por WhatsApp",
    "form.name": "Nombre",
    "form.email": "Email",
    "form.property": "Propiedad o zona",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Mensaje",
    "form.messagePlaceholder": "Fechas, personas, presupuesto o gestión de propiedad...",
    "form.button": "Enviar mensaje",
    "form.note": "Tu mensaje nos llega directamente; te respondemos por email.",
    "email.subject": "Consulta Ebrostay de",
    "email.defaultMessage": "Quiero saber más sobre una vivienda o gestión de propiedad con Ebrostay.",
    "email.propertyFallback": "Sin especificar",
    "detail.back": "Volver a resultados",
    "detail.about": "Sobre esta vivienda",
    "detail.amenities": "Comodidades",
    "detail.location": "Ubicación",
    "detail.locationCopy": "Ubicación aproximada de la vivienda en Zaragoza.",
    "detail.blocked": "Disponibilidad",
    "detail.blockedCopy": "Estas fechas no están disponibles ahora mismo. Para otras fechas, envía tu solicitud.",
    "detail.requestTitle": "¿Te interesa esta vivienda?",
    "detail.requestCopy": "Escríbenos y confirmamos disponibilidad, condiciones y siguiente paso.",
    "detail.emailButton": "Solicitar por email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "O usa el formulario de contacto",
    "whatsapp.message": "Hola Ebrostay, me interesa {property}. ¿Podéis confirmar disponibilidad?",
    "whatsapp.general": "Hola Ebrostay, quiero información sobre una vivienda o gestión de propiedad.",
    "form.sent": "¡Gracias! Hemos recibido tu mensaje y te responderemos pronto.",
    "form.errorSend": "No se pudo enviar. Inténtalo de nuevo o escríbenos por WhatsApp.",
    "auth.login": "Entrar",
    "auth.logout": "Salir",
    "auth.title": "Accede a tu cuenta",
    "auth.copy": "Accede para reservar online, guardar favoritas y consultar tus reservas y facturas.",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.signin": "Iniciar sesión",
    "auth.signup": "Crear cuenta",
    "auth.close": "Cerrar",
    "auth.checkEmail": "Revisa tu correo para confirmar la cuenta.",
    "auth.error": "No se pudo iniciar sesión. Revisa los datos.",
    "auth.signupError": "No se pudo crear la cuenta. Revisa los datos.",
    "auth.admin": "Administración",
    "admin.title": "Panel de administración",
    "admin.copy": "Gestiona anuncios, fotos, precios y disponibilidad. Los cambios se publican al momento.",
    "admin.signinFirst": "Inicia sesión con tu cuenta de administración.",
    "admin.notAdmin": "Tu cuenta no tiene permisos de administración.",
    "admin.notConfigured": "Supabase no está configurado todavía. Completa supabase-config.js.",
    "admin.blocks": "Periodos reservados",
    "admin.noBlocks": "Sin periodos reservados.",
    "admin.from": "Desde",
    "admin.to": "Hasta",
    "admin.add": "Añadir periodo",
    "admin.delete": "Eliminar",
    "admin.availableFrom": "Disponible desde",
    "admin.save": "Guardar",
    "admin.saved": "Guardado.",
    "admin.error": "No se pudo guardar. Inténtalo de nuevo.",
    "admin.back": "Volver al sitio",
    "admin.editDetails": "Editar detalles del anuncio",
    "admin.photos": "Fotos",
    "admin.addPhotos": "Subir fotos",
    "admin.uploading": "Subiendo fotos...",
    "admin.noPhotos": "Sin fotos todavía. Las viviendas sin fotos muestran una imagen genérica.",
    "admin.cover": "Portada",
    "admin.makeCover": "Hacer portada",
    "admin.field.name": "Nombre del anuncio",
    "admin.field.areaEs": "Zona (español)",
    "admin.field.areaEn": "Zona (inglés)",
    "admin.field.copyEs": "Descripción corta (español)",
    "admin.field.copyEn": "Descripción corta (inglés)",
    "admin.field.detailsEs": "Descripción completa (español)",
    "admin.field.detailsEn": "Descripción completa (inglés)",
    "admin.field.priceLabel": "Precio mostrado (ej. 950 EUR)",
    "admin.field.priceNumber": "Precio numérico (para filtros)",
    "admin.field.priceNoteEs": "Nota de precio (español, opcional)",
    "admin.field.priceNoteEn": "Nota de precio (inglés, opcional)",
    "admin.field.guests": "Capacidad (personas)",
    "admin.field.rating": "Valoración (0-5)",
    "admin.field.type": "Tipo de vivienda",
    "admin.field.addressKey": "Grupo de dirección (pedro, movera...)",
    "admin.field.lat": "Latitud",
    "admin.field.lng": "Longitud",
    "admin.field.city": "Ciudad",
    "admin.field.amenities": "Comodidades",
    "admin.flag.isNew": "Novedad",
    "admin.flag.checked": "Verificada",
    "admin.flag.deposit": "Depósito protegido",
    "admin.flag.bills": "Gastos incluidos",
    "admin.flag.published": "Publicada en la web",
    "admin.published": "Publicada",
    "admin.unpublished": "No publicada",
    "admin.guestsUnit": "personas",
    "admin.availability": "Disponibilidad",
    "admin.saveChanges": "Guardar cambios",
    "admin.section.basic": "Información básica",
    "admin.section.price": "Precio",
    "admin.section.textsEs": "Textos en español",
    "admin.section.textsEn": "Textos en inglés",
    "admin.section.location": "Ubicación",
    "admin.section.status": "Estado",
    "admin.field.address": "Dirección",
    "admin.geocodePlaceholder": "Calle y número, ciudad (ej. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Buscar coordenadas",
    "admin.geocodeSearching": "Buscando la dirección...",
    "admin.geocodeNone": "No se encontró la dirección. Prueba con más detalle.",
    "admin.geocodeFound": "Coordenadas rellenadas para:",
    "admin.geocodeError": "No se pudo buscar ahora mismo. Inténtalo de nuevo.",
    "admin.geocodeHint": "Escribe la dirección y pulsa Buscar: la latitud y longitud (la chincheta del mapa) se rellenan solas. Después pulsa Guardar cambios.",
    "admin.field.bedrooms": "Habitaciones",
    "admin.field.bathrooms": "Baños",
    "admin.field.size": "Superficie (m²)",
    "admin.field.floor": "Planta (0 = baja)",
    "admin.section.conditions": "Condiciones",
    "admin.field.minStay": "Estancia mínima (meses)",
    "admin.field.maxStay": "Estancia máxima (meses)",
    "admin.field.deposit": "Fianza (EUR)",
    "admin.field.upfront": "Renta por adelantado (EUR)",
    "admin.field.utilitiesCap": "Límite de suministros (EUR/mes)",
    "admin.field.energy": "Certificado energético",
    "admin.field.video": "Enlace de vídeo (opcional)",
    "admin.field.bedsEs": "Camas (español, ej. 2 dobles y 1 individual)",
    "admin.field.bedsEn": "Camas (inglés)",
    "admin.energyNone": "Sin especificar",
    "admin.flag.pets": "Mascotas permitidas",
    "admin.flag.smoking": "Se permite fumar",
    "admin.flag.couples": "Parejas permitidas",
    "admin.flag.selfCheckin": "Autoentrada (lockbox)",
    "admin.field.guestEmail": "Email del huésped (opcional)",
    "admin.guestNotFound": "No existe ningún usuario registrado con ese email.",
    "admin.guest": "Huésped",
    "admin.users": "Usuarios",
    "admin.usersCopy": "Cuentas registradas. Las cuentas desactivadas se pueden eliminar definitivamente (las reservas pagadas se conservan).",
    "admin.deactivatedChip": "Desactivada",
    "admin.adminChip": "Admin",
    "admin.bookingsCount": "Reservas: {count}",
    "admin.deleteUser": "Eliminar",
    "admin.deleteUserConfirm": "¿Seguro? Pulsa otra vez",
    "admin.userDeleted": "Usuario eliminado.",
    "admin.ai.section": "Autocompletar con IA",
    "admin.ai.intro": "Sube un PDF u otro archivo con la descripción de la vivienda, o pega el texto, y la IA rellenará los campos del formulario. Revisa todo antes de guardar.",
    "admin.ai.file": "Elegir archivo (PDF, imagen o texto)",
    "admin.ai.paste": "...o pega aquí el texto de la descripción",
    "admin.ai.pastePlaceholder": "Pega aquí la descripción de la vivienda...",
    "admin.ai.autofill": "Rellenar campos con IA",
    "admin.ai.reading": "Leyendo el archivo...",
    "admin.ai.ocr": "Leyendo páginas escaneadas con OCR (puede tardar un poco)",
    "admin.ai.thinking": "La IA está analizando la descripción...",
    "admin.ai.filled": "Campos rellenados. Revísalos y pulsa Guardar cambios.",
    "admin.ai.noText": "No se pudo leer texto del archivo (¿PDF escaneado?). Pega el texto manualmente.",
    "admin.ai.empty": "Añade un archivo o pega algo de texto primero.",
    "admin.ai.error": "La IA no está disponible ahora mismo. Inténtalo de nuevo.",
    "admin.ai.notConfigured": "La IA no está configurada (falta la clave de DeepSeek en el servidor).",
    "admin.ai.autoTranslate": "Traducir ES↔EN automáticamente al editar un campo",
    "admin.ai.translating": "Traduciendo...",
    "admin.ai.translateOne": "Traducir al otro idioma"
  },
  en: {
    "meta.title": "Ebrostay | Mid-term corporate rentals in Zaragoza",
    "meta.description": "Ebrostay manages furnished mid-term homes in Zaragoza for companies and professionals, and full management for owners. The bridge between both.",
    "nav.search": "Search",
    "nav.how": "How it works",
    "nav.owners": "Owners",
    "nav.contact": "Contact",
    "nav.cta": "List a home",
    "hero.imageAlt": "Furnished apartment in Zaragoza",
    "hero.kicker": "Mid-term corporate housing, 100% digital",
    "hero.title": "Book your home in Zaragoza in minutes.",
    "hero.copy": "Furnished, verified homes for stays of 1 to 12 months — built for relocating teams and professionals. Transparent total price, online booking and payment, one contact from enquiry to check-out.",
    "hero.trust1": "Verified homes",
    "hero.trust2": "Total price, no surprises",
    "hero.trust3": "Online booking & payment",
    "search.city": "City",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Move-in",
    "search.moveOut": "Move-out",
    "search.guests": "People",
    "search.button": "Search",
    "market.kicker": "Search",
    "market.title": "Available homes in Zaragoza",
    "filters.city": "City",
    "filters.checkIn": "Move-in",
    "filters.checkOut": "Move-out",
    "filters.guests": "People",
    "filters.type": "Home type",
    "filters.typeAll": "All",
    "filters.typeApartment": "Apartment",
    "filters.typeRoom": "Room",
    "filters.typeHome": "House",
    "filters.budget": "Maximum monthly budget",
    "filters.anyBudget": "No limit",
    "filters.mustHave": "Must-have",
    "filters.sort": "Sort",
    "filters.sortBest": "Best match",
    "filters.sortPrice": "Lowest price",
    "filters.sortNew": "New arrivals",
    "filters.apply": "Apply filters",
    "filters.reset": "Reset",
    "filters.show": "Filters",
    "quick.verified": "Verified",
    "quick.bills": "Bills included",
    "quick.deposit": "Refundable deposit",
    "status.all": "Showing {count} managed homes.",
    "status.matches": "{count} homes found.",
    "status.one": "1 home found.",
    "status.none": "No homes match those filters.",
    "status.invalid": "Move-out must be after move-in.",
    "listing.available": "Available",
    "listing.unavailable": "Unavailable",
    "listing.capacity": "Up to {guests} people",
    "listing.price": "{price}/month",
    "listing.from": "Available from {date}",
    "listing.rating": "{rating} rating",
    "listing.view": "View home",
    "listing.map": "Map",
    "listing.favorite": "Save",
    "listing.saved": "Saved",
    "listing.request": "Request",
    "listing.book": "Book",
    "badge.checked": "Verified",
    "badge.deposit": "Refundable deposit",
    "badge.bills": "Bills included",
    "type.apartment": "Apartment",
    "type.room": "Room",
    "type.home": "House",
    "amenity.wifi": "wifi",
    "amenity.desk": "desk",
    "amenity.balcony": "balcony",
    "amenity.lift": "lift",
    "amenity.ac": "air conditioning",
    "amenity.heating": "heating",
    "amenity.kitchen": "equipped kitchen",
    "amenity.terrace": "terrace",
    "amenity.washer": "washing machine",
    "amenity.dishwasher": "dishwasher",
    "amenity.tv": "TV",
    "amenity.microwave": "microwave",
    "amenity.oven": "oven",
    "amenity.parking": "parking",
    "spec.bedroom": "1 bedroom",
    "spec.bedrooms": "{count} bedrooms",
    "spec.bathroom": "1 bathroom",
    "spec.bathrooms": "{count} bathrooms",
    "spec.size": "{size} m²",
    "spec.floor": "Floor {floor}",
    "spec.groundFloor": "Ground floor",
    "detail.conditions": "Conditions",
    "detail.video": "Watch the video tour",
    "cond.minStay": "Minimum stay",
    "cond.maxStay": "Maximum stay",
    "cond.month": "1 month",
    "cond.months": "{count} months",
    "cond.deposit": "Deposit",
    "cond.upfront": "Upfront rent",
    "movein.title": "Move-in cost",
    "movein.upfront": "Upfront rent",
    "movein.deposit": "Deposit",
    "movein.total": "Total to move in",
    "cond.eur": "{amount} EUR",
    "cond.utilities": "Utilities cap",
    "cond.eurMonth": "{amount} EUR/month",
    "cond.energy": "Energy certificate",
    "cond.beds": "Beds",
    "cond.pets": "Pets",
    "cond.smoking": "Smoking allowed",
    "cond.couples": "Couples",
    "cond.selfCheckin": "Self check-in with lockbox",
    "common.yes": "Yes",
    "common.no": "No",
    "cal.legend": "Days crossed out in red are not available.",
    "nav.about": "About",
    "about.kicker": "About Ebrostay",
    "about.title": "The bridge between companies and property owners.",
    "about.lead": "Ebrostay is rebuilding mid-term rental management from first principles — best-in-class service for the companies that house their people and the owners who trust us with their property. Rooted in Zaragoza, built for Europe.",
    "about.mvKicker": "Mission & vision",
    "about.mvTitle": "Where we're going, and what we do every day.",
    "about.visionLabel": "Our vision",
    "about.visionCopy": "To become Europe's number one property management company for mid-term corporate rentals — proven first in Zaragoza, then city by city across the continent.",
    "about.missionLabel": "Our mission",
    "about.missionCopy": "To be the bridge between companies and property owners, delivering best-in-class service to both sides — a home that just works for tenants, and returns without the hassle for owners.",
    "about.bridgeKicker": "The bridge",
    "about.bridgeTitle": "A bridge, in every sense.",
    "about.bridgeLead": "Our logo is a bridge, and it carries two meanings. The first is pure Zaragoza: the bridges that cross the Ebro — the river in our name — like the landmark Puente de Piedra that has linked the two banks of the city for centuries.",
    "about.bridgeLead2": "The second is what we do every day: on one side, companies and the people they relocate; on the other, owners and their homes. Ebrostay is the bridge between them, carrying everything in between so neither side has to.",
    "about.bizTag": "For companies & teams",
    "about.bizTitle": "Housing that's ready for business.",
    "about.bizCopy": "Place a team in Zaragoza without the friction. One contact, one clear monthly price, one process from enquiry to check-out.",
    "about.biz1": "Verified, move-in-ready homes for stays of 1 to 12 months",
    "about.biz2": "Corporate-ready contracts, invoicing and VAT handling",
    "about.biz3": "Whole-flat or room-by-room, with named-tenant flexibility",
    "about.bizCta": "Find a home",
    "about.ownerTag": "For property owners",
    "about.ownerTitle": "Your property, on autopilot.",
    "about.ownerCopy": "Full management with zero involvement. We fill, vet, contract, collect and support — you watch the income land in your account.",
    "about.owner1": "Professional listings, dynamic pricing and multichannel reach",
    "about.owner2": "Tenant verification, contracts, payments and deposits handled",
    "about.owner3": "Real-time dashboard and payouts straight to your account",
    "about.ownerCta": "List your property",
    "about.fpKicker": "First principles",
    "about.fpTitle": "We rebuilt property management from the ground up.",
    "about.fpLead": "Traditional management runs on phone calls, paperwork, blind viewings and hidden fees. We broke every sub-area down to first principles and rebuilt it as something digital, transparent and fast.",
    "about.fp1t": "Pricing & transparency",
    "about.fp1c": "One clear monthly price. No hidden commissions, no surprises at signing.",
    "about.fp2t": "Contracts & compliance",
    "about.fp2c": "Correct seasonal contracts, deposits and registration — handled by us.",
    "about.fp3t": "Payments & deposits",
    "about.fp3c": "Secure online payment, automated invoicing and managed deposits.",
    "about.fp4t": "Support & check-in",
    "about.fp4c": "Lockbox self check-in and 24/7 support in Spanish and English.",
    "about.rootsKicker": "Zaragoza → Europe",
    "about.ctaTitle": "Rooted in Zaragoza. Built for Europe.",
    "about.ctaCopy": "We start where we know every street and every commute, then take the same playbook to the next city. Whether you're placing a team or listing a property, you're talking to the same bridge.",
    "about.ctaFind": "Find a home",
    "about.ctaList": "List your property",
    "account.title": "My account",
    "bookings.button": "My account",
    "bookings.title": "My bookings",
    "bookings.copy": "Stays confirmed with your account appear here.",
    "bookings.empty": "You have no bookings linked to your account yet. Once you confirm a stay with us, it will appear here.",
    "bookings.error": "Could not load your bookings. Try again.",
    "book.title": "Book online",
    "book.start": "Check-in",
    "book.end": "Check-out",
    "book.months": "Duration",
    "book.rent": "Rent",
    "book.payNow": "Total due now",
    "book.stay": "Stay",
    "book.button": "Book and pay",
    "book.note": "You pay the full stay, the management commission and the deposit now. The deposit is refundable at the end of the stay.",
    "book.loginFirst": "Sign in on the home page to book.",
    "book.unavailable": "Those dates are not available.",
    "book.notConfigured": "Online payment is not enabled yet. Message us on WhatsApp to confirm your booking.",
    "book.error": "Could not start the payment. Try again.",
    "book.redirecting": "Opening Stripe secure checkout...",
    "book.confirmed": "Booking confirmed! We sent you an email with the details.",
    "book.cancelled": "Payment cancelled. Your booking was not made.",
    "bookings.paidLabel": "Paid",
    "bookings.invoice": "Invoice",
    "bookings.pdf": "PDF",
    "bookings.receipt": "Receipt",
    "bookings.assignedLabel": "Confirmed",
    "account.loading": "Loading your account…",
    "account.signedOutTitle": "Sign in to see your bookings.",
    "account.signedOutCopy": "Your paid and assigned stays, with their invoices and receipts, appear here once you sign in.",
    "account.sessionTitle": "Session & account",
    "account.deactivate": "Deactivate my account",
    "account.deactivateConfirm": "Your account will be deactivated and you will not be able to sign in again. We keep your booking history. Press again to confirm.",
    "account.deactivateError": "Could not deactivate the account. Try again.",
    "account.delete": "Delete my account",
    "account.deleteConfirm": "Sure? This is permanent. Press again to delete.",
    "account.deleteError": "Could not delete the account. Try again.",
    "account.close": "Close",
    "book.minStay": "Minimum stay: {count} months",
    "book.loginCta": "Sign in to book →",
    "nav.privacy": "Privacy",
    "admin.addProperty": "Add property",
    "admin.addPropertyName": "Name of the new property:",
    "detail.floorplan": "Floor plan",
    "detail.floorplanCopy": "Approximate layout of the home.",
    "detail.distancesNote": "Approximate travel times from the home.",
    "landmark.pilar": "Plaza del Pilar (city centre)",
    "landmark.delicias": "Delicias station (AVE)",
    "landmark.plaza": "PLAZA (Logistics Platform)",
    "dist.walk": "Walking",
    "dist.transit": "Public transport (estimated)",
    "dist.car": "By car",
    "admin.floorplan": "Floor plan",
    "admin.makeFloorplan": "Mark as floor plan",
    "admin.unmakeFloorplan": "Unmark floor plan",
    "dist.placeholder": "Your workplace, an address, a place...",
    "dist.calc": "Calculate distance",
    "dist.searching": "Looking up the address…",
    "dist.notFound": "We could not find that address. Try street and number.",
    "admin.floorplans": "Floor plans",
    "admin.addFloorplans": "Add floor plans",
    "admin.noFloorplans": "No floor plans yet.",
    "admin.floorplansCopy": "Shown in their own section of the listing, separate from the photos.",
    "admin.guestInfo": "Tenant information",
    "admin.guestInfoCopy": "Wifi, keys and emergency contact. Only visible to guests with a booking for this home.",
    "share.button": "Share",
    "share.copied": "Link copied to clipboard",
    "share.text": "Check out this home on Ebrostay",
    "nav.menu": "Menu",
    "hero.ownerCta": "Own a property? Earn without lifting a finger →",
    "why.kicker": "Why Ebrostay",
    "why.title": "What neobanks did to banking, we're doing to renting.",
    "why.lead": "All digital, all transparent, automated end to end. We rebuilt every part of renting from first principles — no endless paperwork, no phone calls, no hidden fees. Booking a home should be as easy as opening an account on your phone.",
    "why.c1.title": "Book in minutes",
    "why.c1.copy": "Pick dates, pay online and get your confirmation and invoice instantly. Zero waiting.",
    "why.c2.title": "Total transparency",
    "why.c2.copy": "The price you see is the price you pay: rent, deposit and conditions clear from the first click.",
    "why.c3.title": "Automated end to end",
    "why.c3.copy": "Contract, payment, deposit, check-in and support handled by software. Less friction, fewer errors.",
    "why.c4.title": "Human support, modern channels",
    "why.c4.copy": "WhatsApp, email and your personal dashboard, in Spanish and English. Fast answers, for real.",
    "split.guestTag": "For companies & tenants",
    "split.guestTitle": "Move in without friction",
    "split.guestCopy": "Find, book and move in. Everything a professional or a whole team needs for the stay, in one place.",
    "split.g1": "Verified homes with photos, floor plans and real distances",
    "split.g2": "Secure online booking and payment with a refundable deposit",
    "split.g3": "Wifi, keys and emergency contact in your dashboard",
    "split.guestCta": "Find a home",
    "split.ownerTag": "For owners",
    "split.ownerTitle": "Earn without lifting a finger",
    "split.ownerCopy": "Full management, zero involvement. We fill, we collect, we transfer. You get the money.",
    "split.o1": "Listings, photos, pricing and channels handled by us",
    "split.o2": "Tenant verification, contracts, payments and deposit",
    "split.o3": "Your dashboard with real-time income and payouts to your account",
    "split.ownerCta": "Discover effortless management",
    "owners.metaTitle": "Ebrostay | Effortless rental management for owners",
    "owners.metaDesc": "Ebrostay manages your mid-stay home end to end: listings, tenants, payments, deposit and payouts to your account. You don't lift a finger.",
    "owners.portal": "Owner portal",
    "owners.cta": "I want to join",
    "owners.kicker": "Rental management · Zero touch",
    "owners.heroTitle": "Your home on autopilot. You just collect the money.",
    "owners.heroLead": "Ebrostay is next-generation mid-stay management: digital, transparent and hands-off. We're your bridge to corporate demand: we handle the whole cycle —from listing to the payout in your account— while you watch the income grow from your dashboard.",
    "owners.seeHow": "See how it works",
    "owners.stat1n": "0",
    "owners.stat1l": "hours of management for you",
    "owners.stat2n": "1–12",
    "owners.stat2l": "months per stay",
    "owners.stat3n": "100%",
    "owners.stat3l": "digital and transparent",
    "owners.compareKicker": "The difference",
    "owners.compareTitle": "Traditional management vs. Ebrostay",
    "owners.compareCol0": " ",
    "owners.compareCol1": "On your own / classic agency",
    "owners.cf1": "Listings, photos and pricing",
    "owners.ct1": "You do it, phone photos",
    "owners.ce1": "Professional and optimized by us",
    "owners.cf2": "Finding tenants",
    "owners.ct2": "Calls, viewings, empty weeks",
    "owners.ce2": "Active, multi-channel pipeline",
    "owners.cf3": "Verification and contracts",
    "owners.ct3": "Manual paperwork, legal risk",
    "owners.ce3": "Verification + correct seasonal contract",
    "owners.cf4": "Payments and deposit",
    "owners.ct4": "Manual transfers and reminders",
    "owners.ce4": "Automatic online payment and managed deposit",
    "owners.cf5": "Check-in, cleaning, issues",
    "owners.ct5": "Your phone rings at all hours",
    "owners.ce5": "Check-in, turnover and support handled",
    "owners.cf6": "Your visibility",
    "owners.ct6": "Spreadsheets and guesswork",
    "owners.ce6": "Dashboard with real-time income and bookings",
    "owners.cf7": "Your effort",
    "owners.ct7": "High and constant",
    "owners.ce7": "Zero",
    "owners.featKicker": "Full management",
    "owners.featTitle": "Everything we do for you",
    "owners.f1t": "Professional listing",
    "owners.f1c": "Photos, bilingual copy, floor plans and optimized description.",
    "owners.f2t": "Dynamic pricing",
    "owners.f2c": "Rates tuned to demand to maximize your occupancy.",
    "owners.f3t": "Multi-channel distribution",
    "owners.f3c": "Your home visible where mid-stay tenants search.",
    "owners.f4t": "Tenant verification",
    "owners.f4c": "We screen and validate every guest before confirming.",
    "owners.f5t": "Contracts and compliance",
    "owners.f5c": "Correct seasonal contract, deposit and registration by law.",
    "owners.f6t": "Payments and deposit",
    "owners.f6c": "Secure online payment, deposit handling and automatic invoicing.",
    "owners.f7t": "Check-in and keys",
    "owners.f7c": "Coordinated arrival and self check-in where applicable.",
    "owners.f8t": "Cleaning and turnover",
    "owners.f8c": "Preparation between stays to keep your home spotless.",
    "owners.f9t": "Support and incidents",
    "owners.f9c": "We handle the tenant so your phone stays quiet.",
    "owners.f10t": "Payouts to your account",
    "owners.f10c": "We transfer your income to your IBAN after each booking, clearly itemized.",
    "owners.howKicker": "In 3 steps",
    "owners.howTitle": "Getting started is this easy",
    "owners.h1t": "Tell us about your home",
    "owners.h1c": "Fill in the form. We assess your flat and propose terms, no commitment.",
    "owners.h2t": "We prepare and publish it",
    "owners.h2c": "Photos, copy, pricing and channels. We activate it as soon as it's ready.",
    "owners.h3t": "You get paid from your dashboard",
    "owners.h3c": "Add your IBAN once and receive your income after each stay. Zero admin.",
    "owners.applyKicker": "Join",
    "owners.applyTitle": "Put your home to work",
    "owners.applyCopy": "Leave your details and a team member contacts you within 24h with a tailored proposal. No commitment.",
    "owners.haveAccount": "Already partner with us? Enter your portal →",
    "owners.phone": "Phone",
    "owners.units": "How many homes?",
    "owners.address": "Area or address",
    "owners.msgPlaceholder": "Tell us about your home...",
    "owners.submit": "Send request",
    "owners.note": "We contact you within 24h. No commitment.",
    "owners.sent": "Got it! We'll contact you within 24h.",
    "owners.sentFallback": "Write to info@ebrostay.com and we'll reply right away.",
    "owners.aboutLink": "Benefits",
    "partner.kicker": "Owner portal",
    "partner.title": "Your portfolio, in real time.",
    "partner.signinCopy": "Sign in with the owner account we set up for you to see your homes, income and payout details.",
    "partner.notOwner": "Your account isn't activated as an owner yet. If you'd like us to manage your home, send us a request and we'll activate it.",
    "partner.metricProps": "Homes",
    "partner.metricBookings": "Bookings",
    "partner.metricRevenue": "Booking income (gross)",
    "partner.metricPayout": "Payout details",
    "partner.propsTitle": "Your homes",
    "partner.bookingsTitle": "Recent bookings",
    "partner.payoutTitle": "Payout details (manual alternative)",
    "partner.payoutCopy": "If you prefer a manual transfer, leave your IBAN here. Your details are encrypted and only Ebrostay sees them. We transfer after each confirmed stay.",
    "partner.holder": "Account holder",
    "partner.iban": "IBAN",
    "partner.bank": "Bank",
    "partner.taxId": "Tax ID (NIF/NIE)",
    "partner.billing": "Billing address",
    "partner.notes": "Notes (optional)",
    "partner.savePayout": "Save payout details",
    "partner.noProps": "You have no homes assigned yet.",
    "partner.thStatus": "Status",
    "partner.pending": "Pending",
    "partner.noBookings": "No bookings yet.",
    "partner.payoutSaved": "Payout details saved.",
    "admin.section.owner": "Owner",
    "admin.field.ownerEmail": "Owner email",
    "admin.ownerHint": "The owner will see this home, its bookings and income in their portal. They must have a registered account with that email.",
    "admin.ownerNotFound": "No account exists with that email. Ask the owner to register first.",
    "partner.connectTitle": "Automatic payouts",
    "partner.connectCopy": "Connect your account with Stripe to receive your rents automatically after each booking — no waiting, no manual transfers.",
    "partner.connectChecking": "Checking status…",
    "partner.connectActive": "✓ Automatic payouts active. You receive your rents after each booking.",
    "partner.connectPending": "Onboarding almost done. Stripe is verifying your details.",
    "partner.connectIncomplete": "Onboarding unfinished. Complete the steps to activate payouts.",
    "partner.connectNone": "Activate automatic payouts to get paid without waiting.",
    "partner.connectUnavailable": "Automatic payouts aren't available yet. Meanwhile, use the manual payout details below.",
    "partner.connectStart": "Activate automatic payouts",
    "partner.connectContinue": "Continue onboarding",
    "partner.connectRedirect": "Opening Stripe…",
    "book.commission": "Commission & management (15%, VAT 21% incl.)",
    "book.commissionDiscount": "Long-stay discount (1-month cap)",
    "book.tenants": "Tenants (one per line)",
    "book.tenantsPlaceholder": "Full name of each tenant",
    "book.vatExempt": "✓ With the tenants named, the rent is VAT-exempt.",
    "book.vatCompany": "💡 Add every tenant's name so the rent is VAT-exempt. Booked under a company without named tenants, a 21% VAT applies that the company self-accounts for (we don't charge it).",
    "book.splitNote": "Maximum 11 months per contract. Longer stays use two contracts: book up to 11 months now and we'll help with the extension.",
    "book.minStayError": "The stay is shorter than this home's minimum duration.",
    "book.rangeUnavailable": "Those dates include already-booked days. Pick an available range.",
    "book.justTaken": "Sorry, another user has just booked the property for those dates. Please choose other available dates.",
    "bookings.viewDetails": "View your stay details",
    "booking.back": "Back to my bookings",
    "booking.kicker": "Your booking",
    "booking.notFoundTitle": "We could not find this booking.",
    "booking.notFoundCopy": "Sign in with the account that made the booking and try again.",
    "booking.viewProperty": "View the property listing",
    "booking.guestInfoTitle": "Information for your stay",
    "booking.guestInfoPending": "We will send you the arrival details (wifi, keys and contact) before your check-in.",
    "booking.guestInfoHelp": "Questions? Write to us at",
    "booking.paidAmount": "Paid",
    "booking.status": "Status",
    "booking.reference": "Reference",
    "guest.wifiName": "Wifi network",
    "guest.wifiPassword": "Wifi password",
    "guest.keyPickup": "Key pickup",
    "guest.checkinTime": "Check-in time",
    "guest.checkoutTime": "Check-out time",
    "guest.emergencyPhone": "Emergency phone",
    "guest.notes": "Notes",
    "admin.tabProperties": "Properties",
    "admin.tabBookings": "Bookings",
    "admin.propListCopy": "Click a property to edit its texts, photos, address and availability.",
    "admin.editProperty": "Edit",
    "admin.confirmedBookings": "Confirmed bookings",
    "admin.confirmedCopy": "Bookings paid via Stripe, with confirmation timestamp, guest details and invoice.",
    "admin.assignedStays": "Assigned stays",
    "admin.assignedCopy": "Stays assigned manually to a guest from each property editor.",
    "admin.noBookings": "No bookings yet.",
    "admin.backToPanel": "Back to the panel",
    "admin.th.confirmed": "Confirmed",
    "admin.th.property": "Property",
    "admin.th.checkin": "Check-in",
    "admin.th.checkout": "Check-out",
    "admin.th.months": "Months",
    "admin.th.amount": "Amount",
    "admin.th.name": "Name",
    "admin.th.email": "Email",
    "admin.th.invoice": "Invoice",
    "admin.field.addressFull": "Address (street and number)",
    "admin.addressHint": "The address appears on the listing and the invoice; coordinates are derived automatically on save.",
    "auth.or": "or",
    "auth.signupTitle": "Create your account",
    "auth.signupCopy": "Create your account to book online and manage your stays.",
    "auth.forgot": "Forgot your password?",
    "auth.resetTitle": "Reset password",
    "auth.resetCopy": "Enter your email and we will send you a link to create a new password.",
    "auth.resetSend": "Send link",
    "auth.resetError": "Could not send the email. Check the address and try again.",
    "auth.recoverTitle": "Choose a new password",
    "auth.recoverCopy": "Enter the new password for your account.",
    "auth.recoverSave": "Save password",
    "auth.recoverError": "Could not save the password. Try again.",
    "auth.successEmailTitle": "Check your email",
    "auth.successConfirmCopy": "We sent a confirmation link to {email}. Open it to activate your account, then sign in.",
    "auth.successResetCopy": "We sent a link to {email} to reset your password.",
    "auth.successRecoverTitle": "Password updated",
    "auth.successRecoverCopy": "You can use your new password now.",
    "auth.google": "Continue with Google",
    "auth.microsoft": "Continue with Outlook",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "University - Pedro II el Católico",
    "properties.pedro1.copy": "Furnished flat at Pedro II el Católico 3, prepared for medium-stay rentals in Zaragoza.",
    "properties.pedro1.details": "First-floor left flat in a connected urban location, with equipped kitchen, work area, and local Ebrostay management.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "University - Pedro II el Católico",
    "properties.pedro2.copy": "Second-floor left flat in the same building, practical for professionals, students, or temporary relocations.",
    "properties.pedro2.details": "Furnished home with functional layout, wifi, heating, and local support for arrival and stay.",
    "properties.movera0.name": "Movera 7 - Segunda Planta",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Three private bedrooms at Movera 7 (second floor), ideal for company teams, technicians, and project stays.",
    "properties.movera0.details": "Three private bedrooms with shared living, dining, and equipped kitchen, plus a full bathroom. Expenses included with utilities capped at 50 EUR per room, self check-in by lockbox, and 24/7 support. Whole flat or room by room.",
    "properties.movera0.priceNote": "or 450 EUR/room",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Three private bedrooms at Movera 7, ideal for company teams, technicians, and project stays.",
    "properties.movera1.details": "Three private bedrooms with shared living, dining, and equipped kitchen, full bathroom, and terrace. Expenses included with utilities capped at 50 EUR per room, self check-in by lockbox, and 24/7 support. Whole flat or room by room.",
    "properties.movera1.priceNote": "or 450 EUR/room",
    "map.title": "Homes map",
    "map.copy": "Each pin shows a home's monthly price. Tap a pin to highlight the home or use the buttons to jump to each address.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "How it works",
    "how.title": "Search, book, and arrive with everything clear.",
    "how.step1.title": "Filter",
    "how.step1.copy": "Choose dates, budget, capacity, and amenities to narrow the search.",
    "how.step2.title": "Review",
    "how.step2.copy": "Compare verified homes, details, location, monthly price, and availability.",
    "how.step3.title": "Book",
    "how.step3.copy": "Book and pay online securely: the full stay plus the refundable deposit. Instant confirmation and invoice.",
    "owners.kicker": "For owners",
    "owners.title": "List and operate your home with local help.",
    "owners.copy": "Ebrostay prepares listings, coordinates arrivals, cleaning, issues, and guest communication so your property works better without taking over your day.",
    "contact.kicker": "Contact",
    "contact.title": "Tell us what you need.",
    "contact.copy": "Tell us your dates, group size and budget, or ask about property management. We reply as soon as possible.",
    "contact.whatsapp": "Message us on WhatsApp",
    "form.name": "Name",
    "form.email": "Email",
    "form.property": "Property or area",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Message",
    "form.messagePlaceholder": "Dates, people, budget, or property management...",
    "form.button": "Send message",
    "form.note": "Your message reaches us directly; we reply by email.",
    "email.subject": "Ebrostay inquiry from",
    "email.defaultMessage": "I would like to know more about a home or property management with Ebrostay.",
    "email.propertyFallback": "Not specified",
    "detail.back": "Back to results",
    "detail.about": "About this home",
    "detail.amenities": "Amenities",
    "detail.location": "Location",
    "detail.locationCopy": "Approximate location of the home in Zaragoza.",
    "detail.blocked": "Availability",
    "detail.blockedCopy": "These dates are currently unavailable. For other dates, send your request.",
    "detail.requestTitle": "Interested in this home?",
    "detail.requestCopy": "Write to us and we confirm availability, terms, and the next step.",
    "detail.emailButton": "Request by email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "Or use the contact form",
    "whatsapp.message": "Hello Ebrostay, I am interested in {property}. Could you confirm availability?",
    "whatsapp.general": "Hello Ebrostay, I would like information about a home or property management.",
    "form.sent": "Thank you! We received your message and will reply soon.",
    "form.errorSend": "Could not send. Try again or message us on WhatsApp.",
    "auth.login": "Sign in",
    "auth.logout": "Sign out",
    "auth.title": "Access your account",
    "auth.copy": "Sign in to book online, save favourites, and see your bookings and invoices.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signin": "Sign in",
    "auth.signup": "Create account",
    "auth.close": "Close",
    "auth.checkEmail": "Check your email to confirm your account.",
    "auth.error": "Could not sign in. Check your details.",
    "auth.signupError": "Could not create the account. Check your details.",
    "auth.admin": "Admin",
    "admin.title": "Admin panel",
    "admin.copy": "Manage listings, photos, prices, and availability. Changes go live immediately.",
    "admin.signinFirst": "Sign in with your admin account.",
    "admin.notAdmin": "Your account does not have admin permissions.",
    "admin.notConfigured": "Supabase is not configured yet. Fill in supabase-config.js.",
    "admin.blocks": "Booked periods",
    "admin.noBlocks": "No booked periods.",
    "admin.from": "From",
    "admin.to": "To",
    "admin.add": "Add period",
    "admin.delete": "Delete",
    "admin.availableFrom": "Available from",
    "admin.save": "Save",
    "admin.saved": "Saved.",
    "admin.error": "Could not save. Try again.",
    "admin.back": "Back to site",
    "admin.editDetails": "Edit listing details",
    "admin.photos": "Photos",
    "admin.addPhotos": "Upload photos",
    "admin.uploading": "Uploading photos...",
    "admin.noPhotos": "No photos yet. Homes without photos show a generic image.",
    "admin.cover": "Cover",
    "admin.makeCover": "Make cover",
    "admin.field.name": "Listing name",
    "admin.field.areaEs": "Area (Spanish)",
    "admin.field.areaEn": "Area (English)",
    "admin.field.copyEs": "Short description (Spanish)",
    "admin.field.copyEn": "Short description (English)",
    "admin.field.detailsEs": "Full description (Spanish)",
    "admin.field.detailsEn": "Full description (English)",
    "admin.field.priceLabel": "Displayed price (e.g. 950 EUR)",
    "admin.field.priceNumber": "Numeric price (for filters)",
    "admin.field.priceNoteEs": "Price note (Spanish, optional)",
    "admin.field.priceNoteEn": "Price note (English, optional)",
    "admin.field.guests": "Capacity (people)",
    "admin.field.rating": "Rating (0-5)",
    "admin.field.type": "Home type",
    "admin.field.addressKey": "Address group (pedro, movera...)",
    "admin.field.lat": "Latitude",
    "admin.field.lng": "Longitude",
    "admin.field.city": "City",
    "admin.field.amenities": "Amenities",
    "admin.flag.isNew": "New arrival",
    "admin.flag.checked": "Verified",
    "admin.flag.deposit": "Deposit protected",
    "admin.flag.bills": "Bills included",
    "admin.flag.published": "Published on the website",
    "admin.published": "Published",
    "admin.unpublished": "Not published",
    "admin.guestsUnit": "guests",
    "admin.availability": "Availability",
    "admin.saveChanges": "Save changes",
    "admin.section.basic": "Basic information",
    "admin.section.price": "Price",
    "admin.section.textsEs": "Spanish texts",
    "admin.section.textsEn": "English texts",
    "admin.section.location": "Location",
    "admin.section.status": "Status",
    "admin.field.address": "Address",
    "admin.geocodePlaceholder": "Street and number, city (e.g. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Find coordinates",
    "admin.geocodeSearching": "Searching for the address...",
    "admin.geocodeNone": "Address not found. Try adding more detail.",
    "admin.geocodeFound": "Coordinates filled in for:",
    "admin.geocodeError": "Could not search right now. Try again.",
    "admin.geocodeHint": "Type the address and press Find: latitude and longitude (the map pin) are filled in automatically. Then press Save changes.",
    "admin.field.bedrooms": "Bedrooms",
    "admin.field.bathrooms": "Bathrooms",
    "admin.field.size": "Size (m²)",
    "admin.field.floor": "Floor (0 = ground)",
    "admin.section.conditions": "Conditions",
    "admin.field.minStay": "Minimum stay (months)",
    "admin.field.maxStay": "Maximum stay (months)",
    "admin.field.deposit": "Deposit (EUR)",
    "admin.field.upfront": "Upfront rent (EUR)",
    "admin.field.utilitiesCap": "Utilities cap (EUR/month)",
    "admin.field.energy": "Energy certificate",
    "admin.field.video": "Video link (optional)",
    "admin.field.bedsEs": "Beds (Spanish, e.g. 2 dobles y 1 individual)",
    "admin.field.bedsEn": "Beds (English)",
    "admin.energyNone": "Not specified",
    "admin.flag.pets": "Pets allowed",
    "admin.flag.smoking": "Smoking allowed",
    "admin.flag.couples": "Couples allowed",
    "admin.flag.selfCheckin": "Self check-in (lockbox)",
    "admin.field.guestEmail": "Guest email (optional)",
    "admin.guestNotFound": "No registered user with that email.",
    "admin.guest": "Guest",
    "admin.users": "Users",
    "admin.usersCopy": "Registered accounts. Deactivated accounts can be deleted permanently (paid bookings are kept).",
    "admin.deactivatedChip": "Deactivated",
    "admin.adminChip": "Admin",
    "admin.bookingsCount": "Bookings: {count}",
    "admin.deleteUser": "Delete",
    "admin.deleteUserConfirm": "Sure? Press again",
    "admin.userDeleted": "User deleted.",
    "admin.ai.section": "Autofill with AI",
    "admin.ai.intro": "Upload a PDF or other file describing the home, or paste the text, and AI will fill in the form fields. Review everything before saving.",
    "admin.ai.file": "Choose file (PDF, image or text)",
    "admin.ai.paste": "...or paste the description text here",
    "admin.ai.pastePlaceholder": "Paste the property description here...",
    "admin.ai.autofill": "Autofill fields with AI",
    "admin.ai.reading": "Reading the file...",
    "admin.ai.ocr": "Reading scanned pages with OCR (this can take a moment)",
    "admin.ai.thinking": "AI is analysing the description...",
    "admin.ai.filled": "Fields filled in. Review them and press Save changes.",
    "admin.ai.noText": "Couldn't read text from the file (scanned PDF?). Paste the text manually.",
    "admin.ai.empty": "Add a file or paste some text first.",
    "admin.ai.error": "AI is not available right now. Try again.",
    "admin.ai.notConfigured": "AI is not configured (DeepSeek key missing on the server).",
    "admin.ai.autoTranslate": "Auto-translate ES↔EN when I edit a field",
    "admin.ai.translating": "Translating...",
    "admin.ai.translateOne": "Translate to the other language"
  }
};

const properties = [
  {
    id: "pedro1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro1.name",
    areaKey: "properties.pedro1.area",
    copyKey: "properties.pedro1.copy",
    detailsKey: "properties.pedro1.details",
    lat: 41.65393,
    lng: -0.90783,
    guests: 4,
    price: "950 EUR",
    priceNumber: 950,
    rating: 4.8,
    floorNumber: 1,
    availableFrom: "2026-07-01",
    isNew: false,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen"],
    unavailable: [["2026-06-20", "2026-06-24"], ["2026-07-04", "2026-07-10"], ["2026-08-12", "2026-08-18"]]
  },
  {
    id: "pedro2",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro2.name",
    areaKey: "properties.pedro2.area",
    copyKey: "properties.pedro2.copy",
    detailsKey: "properties.pedro2.details",
    lat: 41.65416,
    lng: -0.90756,
    guests: 4,
    price: "980 EUR",
    priceNumber: 980,
    rating: 4.7,
    floorNumber: 2,
    availableFrom: "2026-07-10",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen", "ac"],
    unavailable: [["2026-06-27", "2026-07-03"], ["2026-07-18", "2026-07-22"], ["2026-08-10", "2026-08-14"]]
  },
  {
    id: "movera0",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera0.name",
    areaKey: "properties.movera0.area",
    copyKey: "properties.movera0.copy",
    detailsKey: "properties.movera0.details",
    priceNoteKey: "properties.movera0.priceNote",
    lat: 41.64929,
    lng: -0.82209,
    guests: 3,
    price: "1.350 EUR",
    priceNumber: 1350,
    rating: 4.9,
    floorNumber: 2,
    bedrooms: 3,
    bathrooms: 1,
    utilitiesCapEur: 50,
    selfCheckin: true,
    minStayMonths: 1,
    availableFrom: "2026-07-01",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "heating", "kitchen"],
    photos: [
      "assets/movera-second-hero.jpg",
      "assets/movera-second-bedroom-1.jpg",
      "assets/movera-second-bedroom-2.jpg",
      "assets/movera-second-bedroom-3.jpg",
      "assets/movera-second-bathroom.jpg"
    ],
    floorplans: ["assets/movera-second-floorplan.png"],
    unavailable: [["2026-07-26", "2026-08-02"]]
  },
  {
    id: "movera1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera1.name",
    areaKey: "properties.movera1.area",
    copyKey: "properties.movera1.copy",
    detailsKey: "properties.movera1.details",
    priceNoteKey: "properties.movera1.priceNote",
    lat: 41.64952,
    lng: -0.82182,
    guests: 3,
    price: "1.350 EUR",
    priceNumber: 1350,
    rating: 4.7,
    floorNumber: 1,
    bedrooms: 3,
    bathrooms: 1,
    utilitiesCapEur: 50,
    selfCheckin: true,
    minStayMonths: 1,
    availableFrom: "2026-07-01",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "heating", "kitchen", "terrace"],
    photos: [
      "assets/movera-first-hero.jpg",
      "assets/movera-first-bedroom-1.jpg",
      "assets/movera-first-bedroom-2.jpg",
      "assets/movera-first-bathroom.jpg"
    ],
    floorplans: ["assets/movera-first-floorplan.png"],
    unavailable: [["2026-06-22", "2026-06-29"], ["2026-08-01", "2026-08-16"]]
  }
];

const addressLocations = {
  pedro: { lat: 41.65393, lng: -0.90783 },
  movera: { lat: 41.64929, lng: -0.82209 }
};

function whatsappLink(text) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;
}

// Spec line shared by the listing cards and the property page:
// "3 habitaciones · 1 baño · 70 m² · Planta 1" (only fields that exist)
function propertySpecs(property, translate, interpolateFn) {
  const specs = [];
  if (property.bedrooms != null) {
    specs.push(property.bedrooms === 1 ? translate("spec.bedroom") : interpolateFn("spec.bedrooms", { count: property.bedrooms }));
  }
  if (property.bathrooms != null) {
    specs.push(property.bathrooms === 1 ? translate("spec.bathroom") : interpolateFn("spec.bathrooms", { count: property.bathrooms }));
  }
  if (property.sizeM2 != null) specs.push(interpolateFn("spec.size", { size: property.sizeM2 }));
  if (property.floorNumber != null) {
    specs.push(property.floorNumber === 0 ? translate("spec.groundFloor") : interpolateFn("spec.floor", { floor: property.floorNumber }));
  }
  return specs;
}
