const CONTACT_EMAIL = "info@ebrostay.com";
const WHATSAPP_NUMBER = "34678715418";

const translations = {
  es: {
    "meta.title": "Ebrostay | Alquileres verificados en Zaragoza",
    "meta.description": "Busca viviendas amuebladas y gestionadas por Ebrostay en Zaragoza. Filtra por fechas, presupuesto, capacidad y tipo de propiedad.",
    "nav.search": "Buscar",
    "nav.how": "Cómo funciona",
    "nav.owners": "Propietarios",
    "nav.contact": "Contacto",
    "nav.cta": "Publicar vivienda",
    "hero.imageAlt": "Apartamento amueblado en Zaragoza",
    "hero.kicker": "Alquileres de media estancia en Zaragoza",
    "hero.title": "Encuentra una vivienda lista para entrar.",
    "hero.copy": "Apartamentos, habitaciones y casas amuebladas con gestión local, disponibilidad clara y soporte antes de llegar.",
    "hero.trust1": "Viviendas verificadas",
    "hero.trust2": "Gestión local",
    "hero.trust3": "Solicitud online",
    "search.city": "Ciudad",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Entrada",
    "search.guests": "Personas",
    "search.button": "Buscar",
    "market.kicker": "Búsqueda",
    "market.title": "Viviendas disponibles en Zaragoza",
    "filters.city": "Ciudad",
    "filters.checkIn": "Entrada",
    "filters.checkOut": "Salida",
    "filters.guests": "Personas",
    "filters.type": "Tipo de vivienda",
    "filters.typeAll": "Todos",
    "filters.typeApartment": "Apartamento",
    "filters.typeRoom": "Habitación",
    "filters.typeHome": "Casa",
    "filters.budget": "Presupuesto mensual máximo",
    "filters.anyBudget": "Sin límite",
    "filters.mustHave": "Imprescindible",
    "filters.sort": "Ordenar",
    "filters.sortBest": "Mejor opción",
    "filters.sortPrice": "Precio más bajo",
    "filters.sortNew": "Novedades",
    "filters.apply": "Aplicar filtros",
    "filters.reset": "Reiniciar",
    "filters.show": "Filtros",
    "quick.verified": "Verificadas",
    "quick.bills": "Gastos incluidos",
    "quick.deposit": "Depósito protegido",
    "status.all": "Mostrando {count} viviendas gestionadas.",
    "status.matches": "{count} viviendas encontradas.",
    "status.one": "1 vivienda encontrada.",
    "status.none": "No hay viviendas para esos filtros.",
    "status.invalid": "La fecha de salida debe ser posterior a la entrada.",
    "listing.available": "Disponible",
    "listing.unavailable": "No disponible",
    "listing.capacity": "Hasta {guests} personas",
    "listing.price": "{price}/mes",
    "listing.from": "Disponible desde {date}",
    "listing.rating": "{rating} valoración",
    "listing.view": "Ver vivienda",
    "listing.map": "Mapa",
    "listing.favorite": "Guardar",
    "listing.saved": "Guardado",
    "listing.request": "Solicitar",
    "badge.checked": "Verificada",
    "badge.deposit": "Depósito protegido",
    "badge.bills": "Gastos incluidos",
    "type.apartment": "Apartamento",
    "type.room": "Habitación",
    "type.home": "Casa",
    "amenity.wifi": "wifi",
    "amenity.desk": "mesa de trabajo",
    "amenity.balcony": "balcón",
    "amenity.lift": "ascensor",
    "amenity.ac": "aire acondicionado",
    "amenity.heating": "calefacción",
    "amenity.kitchen": "cocina equipada",
    "amenity.terrace": "terraza",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "Universidad - Pedro II el Católico",
    "properties.pedro1.copy": "Piso amueblado en Pedro II el Católico 3, preparado para estancias de media duración en Zaragoza.",
    "properties.pedro1.details": "Primero izquierda en una ubicación urbana y bien comunicada, con cocina equipada, zona de trabajo y gestión local Ebrostay.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "Universidad - Pedro II el Católico",
    "properties.pedro2.copy": "Segundo izquierda en el mismo edificio, una opción práctica para profesionales, estudiantes o traslados temporales.",
    "properties.pedro2.details": "Vivienda amueblada con distribución funcional, wifi, calefacción y soporte local para llegada y estancia.",
    "properties.movera0.name": "Movera 7 - Planta Baja",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Piso en planta baja en Movera 7, pensado para estancias tranquilas con acceso cómodo.",
    "properties.movera0.details": "Opción de planta baja con cocina equipada, buena capacidad y gestión cercana para incidencias o necesidades durante la estancia.",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Piso de 3 habitaciones privadas en Movera 7, ideal para equipos de empresa, técnicos y estancias por proyecto.",
    "properties.movera1.details": "Tres dormitorios privados con salón, comedor y cocina equipada compartidos, baño completo y terraza. Gastos incluidos con suministros limitados a 50 EUR por habitación, autoentrada con lockbox y soporte 24/7. Piso completo o por habitaciones.",
    "properties.movera1.priceNote": "o 450 EUR/habitación",
    "map.title": "Mapa de viviendas",
    "map.copy": "Cada pin muestra el precio mensual de una vivienda. Toca un pin para resaltar la vivienda o usa los botones para ir a cada dirección.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "Cómo funciona",
    "how.title": "Busca, solicita y llega con todo claro.",
    "how.step1.title": "Filtra",
    "how.step1.copy": "Elige fechas, presupuesto, capacidad y comodidades para reducir la búsqueda.",
    "how.step2.title": "Revisa",
    "how.step2.copy": "Compara viviendas verificadas, detalles, ubicación, precio mensual y disponibilidad.",
    "how.step3.title": "Solicita",
    "how.step3.copy": "Envía una solicitud y Ebrostay confirma disponibilidad, condiciones y siguiente paso.",
    "owners.kicker": "Para propietarios",
    "owners.title": "Publica y opera tu vivienda con ayuda local.",
    "owners.copy": "Ebrostay prepara anuncios, coordina entradas, limpiezas, incidencias y comunicación con huéspedes para que tu propiedad funcione mejor sin absorber tu día.",
    "contact.kicker": "Contacto",
    "contact.title": "Cuéntanos qué necesitas.",
    "contact.copy": "El formulario prepara un correo directo con la vivienda o consulta seleccionada.",
    "contact.whatsapp": "Escríbenos por WhatsApp",
    "form.name": "Nombre",
    "form.email": "Email",
    "form.property": "Propiedad o zona",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Mensaje",
    "form.messagePlaceholder": "Fechas, personas, presupuesto o gestión de propiedad...",
    "form.button": "Preparar correo",
    "form.note": "Se abrirá tu app de correo con el mensaje listo para enviar.",
    "email.subject": "Consulta Ebrostay de",
    "email.defaultMessage": "Quiero saber más sobre una vivienda o gestión de propiedad con Ebrostay.",
    "email.propertyFallback": "Sin especificar",
    "detail.back": "Volver a resultados",
    "detail.about": "Sobre esta vivienda",
    "detail.amenities": "Comodidades",
    "detail.location": "Ubicación",
    "detail.locationCopy": "Ubicación aproximada de la vivienda en Zaragoza.",
    "detail.blocked": "Fechas ya reservadas",
    "detail.blockedCopy": "Estas fechas no están disponibles ahora mismo. Para otras fechas, envía tu solicitud.",
    "detail.requestTitle": "¿Te interesa esta vivienda?",
    "detail.requestCopy": "Escríbenos y confirmamos disponibilidad, condiciones y siguiente paso.",
    "detail.emailButton": "Solicitar por email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "O usa el formulario de contacto",
    "whatsapp.message": "Hola Ebrostay, me interesa {property}. ¿Podéis confirmar disponibilidad?",
    "whatsapp.general": "Hola Ebrostay, quiero información sobre una vivienda o gestión de propiedad.",
    "form.sent": "¡Gracias! Hemos recibido tu mensaje y te responderemos pronto.",
    "form.errorSend": "No se pudo enviar. Inténtalo de nuevo o escríbenos por WhatsApp.",
    "auth.login": "Entrar",
    "auth.logout": "Salir",
    "auth.title": "Accede a tu cuenta",
    "auth.copy": "Guarda viviendas para verlas más tarde desde cualquier dispositivo.",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.signin": "Iniciar sesión",
    "auth.signup": "Crear cuenta",
    "auth.close": "Cerrar",
    "auth.checkEmail": "Revisa tu correo para confirmar la cuenta.",
    "auth.error": "No se pudo iniciar sesión. Revisa los datos.",
    "auth.signupError": "No se pudo crear la cuenta. Revisa los datos.",
    "auth.admin": "Administración",
    "admin.title": "Panel de administración",
    "admin.copy": "Gestiona anuncios, fotos, precios y disponibilidad. Los cambios se publican al momento.",
    "admin.signinFirst": "Inicia sesión con tu cuenta de administración.",
    "admin.notAdmin": "Tu cuenta no tiene permisos de administración.",
    "admin.notConfigured": "Supabase no está configurado todavía. Completa supabase-config.js.",
    "admin.blocks": "Periodos reservados",
    "admin.noBlocks": "Sin periodos reservados.",
    "admin.from": "Desde",
    "admin.to": "Hasta",
    "admin.add": "Añadir periodo",
    "admin.delete": "Eliminar",
    "admin.availableFrom": "Disponible desde",
    "admin.save": "Guardar",
    "admin.saved": "Guardado.",
    "admin.error": "No se pudo guardar. Inténtalo de nuevo.",
    "admin.back": "Volver al sitio",
    "admin.editDetails": "Editar detalles del anuncio",
    "admin.photos": "Fotos",
    "admin.addPhotos": "Subir fotos",
    "admin.uploading": "Subiendo fotos...",
    "admin.noPhotos": "Sin fotos todavía. Las viviendas sin fotos muestran una imagen genérica.",
    "admin.cover": "Portada",
    "admin.makeCover": "Hacer portada",
    "admin.field.name": "Nombre del anuncio",
    "admin.field.areaEs": "Zona (español)",
    "admin.field.areaEn": "Zona (inglés)",
    "admin.field.copyEs": "Descripción corta (español)",
    "admin.field.copyEn": "Descripción corta (inglés)",
    "admin.field.detailsEs": "Descripción completa (español)",
    "admin.field.detailsEn": "Descripción completa (inglés)",
    "admin.field.priceLabel": "Precio mostrado (ej. 950 EUR)",
    "admin.field.priceNumber": "Precio numérico (para filtros)",
    "admin.field.priceNoteEs": "Nota de precio (español, opcional)",
    "admin.field.priceNoteEn": "Nota de precio (inglés, opcional)",
    "admin.field.guests": "Capacidad (personas)",
    "admin.field.rating": "Valoración (0-5)",
    "admin.field.type": "Tipo de vivienda",
    "admin.field.addressKey": "Grupo de dirección (pedro, movera...)",
    "admin.field.lat": "Latitud",
    "admin.field.lng": "Longitud",
    "admin.field.city": "Ciudad",
    "admin.field.amenities": "Comodidades",
    "admin.flag.isNew": "Novedad",
    "admin.flag.checked": "Verificada",
    "admin.flag.deposit": "Depósito protegido",
    "admin.flag.bills": "Gastos incluidos",
    "admin.flag.published": "Publicada en la web",
    "admin.published": "Publicada",
    "admin.unpublished": "No publicada",
    "admin.guestsUnit": "personas",
    "admin.availability": "Disponibilidad",
    "admin.saveChanges": "Guardar cambios",
    "admin.section.basic": "Información básica",
    "admin.section.price": "Precio",
    "admin.section.textsEs": "Textos en español",
    "admin.section.textsEn": "Textos en inglés",
    "admin.section.location": "Ubicación",
    "admin.section.status": "Estado",
    "admin.field.address": "Dirección",
    "admin.geocodePlaceholder": "Calle y número, ciudad (ej. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Buscar coordenadas",
    "admin.geocodeSearching": "Buscando la dirección...",
    "admin.geocodeNone": "No se encontró la dirección. Prueba con más detalle.",
    "admin.geocodeFound": "Coordenadas rellenadas para:",
    "admin.geocodeError": "No se pudo buscar ahora mismo. Inténtalo de nuevo.",
    "admin.geocodeHint": "Escribe la dirección y pulsa Buscar: la latitud y longitud (la chincheta del mapa) se rellenan solas. Después pulsa Guardar cambios."
  },
  en: {
    "meta.title": "Ebrostay | Verified rentals in Zaragoza",
    "meta.description": "Search furnished homes managed by Ebrostay in Zaragoza. Filter by dates, budget, capacity, and property type.",
    "nav.search": "Search",
    "nav.how": "How it works",
    "nav.owners": "Owners",
    "nav.contact": "Contact",
    "nav.cta": "List a home",
    "hero.imageAlt": "Furnished apartment in Zaragoza",
    "hero.kicker": "Medium-stay rentals in Zaragoza",
    "hero.title": "Find a home ready to move into.",
    "hero.copy": "Furnished apartments, rooms, and homes with local management, clear availability, and support before arrival.",
    "hero.trust1": "Verified homes",
    "hero.trust2": "Local management",
    "hero.trust3": "Online request",
    "search.city": "City",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Move-in",
    "search.guests": "People",
    "search.button": "Search",
    "market.kicker": "Search",
    "market.title": "Available homes in Zaragoza",
    "filters.city": "City",
    "filters.checkIn": "Move-in",
    "filters.checkOut": "Move-out",
    "filters.guests": "People",
    "filters.type": "Home type",
    "filters.typeAll": "All",
    "filters.typeApartment": "Apartment",
    "filters.typeRoom": "Room",
    "filters.typeHome": "House",
    "filters.budget": "Maximum monthly budget",
    "filters.anyBudget": "No limit",
    "filters.mustHave": "Must-have",
    "filters.sort": "Sort",
    "filters.sortBest": "Best match",
    "filters.sortPrice": "Lowest price",
    "filters.sortNew": "New arrivals",
    "filters.apply": "Apply filters",
    "filters.reset": "Reset",
    "filters.show": "Filters",
    "quick.verified": "Verified",
    "quick.bills": "Bills included",
    "quick.deposit": "Deposit protected",
    "status.all": "Showing {count} managed homes.",
    "status.matches": "{count} homes found.",
    "status.one": "1 home found.",
    "status.none": "No homes match those filters.",
    "status.invalid": "Move-out must be after move-in.",
    "listing.available": "Available",
    "listing.unavailable": "Unavailable",
    "listing.capacity": "Up to {guests} people",
    "listing.price": "{price}/month",
    "listing.from": "Available from {date}",
    "listing.rating": "{rating} rating",
    "listing.view": "View home",
    "listing.map": "Map",
    "listing.favorite": "Save",
    "listing.saved": "Saved",
    "listing.request": "Request",
    "badge.checked": "Verified",
    "badge.deposit": "Deposit protected",
    "badge.bills": "Bills included",
    "type.apartment": "Apartment",
    "type.room": "Room",
    "type.home": "House",
    "amenity.wifi": "wifi",
    "amenity.desk": "desk",
    "amenity.balcony": "balcony",
    "amenity.lift": "lift",
    "amenity.ac": "air conditioning",
    "amenity.heating": "heating",
    "amenity.kitchen": "equipped kitchen",
    "amenity.terrace": "terrace",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "University - Pedro II el Católico",
    "properties.pedro1.copy": "Furnished flat at Pedro II el Católico 3, prepared for medium-stay rentals in Zaragoza.",
    "properties.pedro1.details": "First-floor left flat in a connected urban location, with equipped kitchen, work area, and local Ebrostay management.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "University - Pedro II el Católico",
    "properties.pedro2.copy": "Second-floor left flat in the same building, practical for professionals, students, or temporary relocations.",
    "properties.pedro2.details": "Furnished home with functional layout, wifi, heating, and local support for arrival and stay.",
    "properties.movera0.name": "Movera 7 - Planta Baja",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Ground-floor flat at Movera 7, designed for calmer stays with easy access.",
    "properties.movera0.details": "Ground-floor option with equipped kitchen, good capacity, and local management for issues or needs during the stay.",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Three private bedrooms at Movera 7, ideal for company teams, technicians, and project stays.",
    "properties.movera1.details": "Three private bedrooms with shared living, dining, and equipped kitchen, full bathroom, and terrace. Expenses included with utilities capped at 50 EUR per room, self check-in by lockbox, and 24/7 support. Whole flat or room by room.",
    "properties.movera1.priceNote": "or 450 EUR/room",
    "map.title": "Homes map",
    "map.copy": "Each pin shows a home's monthly price. Tap a pin to highlight the home or use the buttons to jump to each address.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "How it works",
    "how.title": "Search, request, and arrive with clarity.",
    "how.step1.title": "Filter",
    "how.step1.copy": "Choose dates, budget, capacity, and amenities to narrow the search.",
    "how.step2.title": "Review",
    "how.step2.copy": "Compare verified homes, details, location, monthly price, and availability.",
    "how.step3.title": "Request",
    "how.step3.copy": "Send a request and Ebrostay confirms availability, terms, and next step.",
    "owners.kicker": "For owners",
    "owners.title": "List and operate your home with local help.",
    "owners.copy": "Ebrostay prepares listings, coordinates arrivals, cleaning, issues, and guest communication so your property works better without taking over your day.",
    "contact.kicker": "Contact",
    "contact.title": "Tell us what you need.",
    "contact.copy": "The form prepares a direct email with the selected home or inquiry.",
    "contact.whatsapp": "Message us on WhatsApp",
    "form.name": "Name",
    "form.email": "Email",
    "form.property": "Property or area",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Message",
    "form.messagePlaceholder": "Dates, people, budget, or property management...",
    "form.button": "Prepare email",
    "form.note": "Your email app will open with the message ready to send.",
    "email.subject": "Ebrostay inquiry from",
    "email.defaultMessage": "I would like to know more about a home or property management with Ebrostay.",
    "email.propertyFallback": "Not specified",
    "detail.back": "Back to results",
    "detail.about": "About this home",
    "detail.amenities": "Amenities",
    "detail.location": "Location",
    "detail.locationCopy": "Approximate location of the home in Zaragoza.",
    "detail.blocked": "Already booked dates",
    "detail.blockedCopy": "These dates are currently unavailable. For other dates, send your request.",
    "detail.requestTitle": "Interested in this home?",
    "detail.requestCopy": "Write to us and we confirm availability, terms, and the next step.",
    "detail.emailButton": "Request by email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "Or use the contact form",
    "whatsapp.message": "Hello Ebrostay, I am interested in {property}. Could you confirm availability?",
    "whatsapp.general": "Hello Ebrostay, I would like information about a home or property management.",
    "form.sent": "Thank you! We received your message and will reply soon.",
    "form.errorSend": "Could not send. Try again or message us on WhatsApp.",
    "auth.login": "Sign in",
    "auth.logout": "Sign out",
    "auth.title": "Access your account",
    "auth.copy": "Save homes to revisit them later from any device.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signin": "Sign in",
    "auth.signup": "Create account",
    "auth.close": "Close",
    "auth.checkEmail": "Check your email to confirm your account.",
    "auth.error": "Could not sign in. Check your details.",
    "auth.signupError": "Could not create the account. Check your details.",
    "auth.admin": "Admin",
    "admin.title": "Admin panel",
    "admin.copy": "Manage listings, photos, prices, and availability. Changes go live immediately.",
    "admin.signinFirst": "Sign in with your admin account.",
    "admin.notAdmin": "Your account does not have admin permissions.",
    "admin.notConfigured": "Supabase is not configured yet. Fill in supabase-config.js.",
    "admin.blocks": "Booked periods",
    "admin.noBlocks": "No booked periods.",
    "admin.from": "From",
    "admin.to": "To",
    "admin.add": "Add period",
    "admin.delete": "Delete",
    "admin.availableFrom": "Available from",
    "admin.save": "Save",
    "admin.saved": "Saved.",
    "admin.error": "Could not save. Try again.",
    "admin.back": "Back to site",
    "admin.editDetails": "Edit listing details",
    "admin.photos": "Photos",
    "admin.addPhotos": "Upload photos",
    "admin.uploading": "Uploading photos...",
    "admin.noPhotos": "No photos yet. Homes without photos show a generic image.",
    "admin.cover": "Cover",
    "admin.makeCover": "Make cover",
    "admin.field.name": "Listing name",
    "admin.field.areaEs": "Area (Spanish)",
    "admin.field.areaEn": "Area (English)",
    "admin.field.copyEs": "Short description (Spanish)",
    "admin.field.copyEn": "Short description (English)",
    "admin.field.detailsEs": "Full description (Spanish)",
    "admin.field.detailsEn": "Full description (English)",
    "admin.field.priceLabel": "Displayed price (e.g. 950 EUR)",
    "admin.field.priceNumber": "Numeric price (for filters)",
    "admin.field.priceNoteEs": "Price note (Spanish, optional)",
    "admin.field.priceNoteEn": "Price note (English, optional)",
    "admin.field.guests": "Capacity (people)",
    "admin.field.rating": "Rating (0-5)",
    "admin.field.type": "Home type",
    "admin.field.addressKey": "Address group (pedro, movera...)",
    "admin.field.lat": "Latitude",
    "admin.field.lng": "Longitude",
    "admin.field.city": "City",
    "admin.field.amenities": "Amenities",
    "admin.flag.isNew": "New arrival",
    "admin.flag.checked": "Verified",
    "admin.flag.deposit": "Deposit protected",
    "admin.flag.bills": "Bills included",
    "admin.flag.published": "Published on the website",
    "admin.published": "Published",
    "admin.unpublished": "Not published",
    "admin.guestsUnit": "guests",
    "admin.availability": "Availability",
    "admin.saveChanges": "Save changes",
    "admin.section.basic": "Basic information",
    "admin.section.price": "Price",
    "admin.section.textsEs": "Spanish texts",
    "admin.section.textsEn": "English texts",
    "admin.section.location": "Location",
    "admin.section.status": "Status",
    "admin.field.address": "Address",
    "admin.geocodePlaceholder": "Street and number, city (e.g. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Find coordinates",
    "admin.geocodeSearching": "Searching for the address...",
    "admin.geocodeNone": "Address not found. Try adding more detail.",
    "admin.geocodeFound": "Coordinates filled in for:",
    "admin.geocodeError": "Could not search right now. Try again.",
    "admin.geocodeHint": "Type the address and press Find: latitude and longitude (the map pin) are filled in automatically. Then press Save changes."
  }
};

const properties = [
  {
    id: "pedro1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro1.name",
    areaKey: "properties.pedro1.area",
    copyKey: "properties.pedro1.copy",
    detailsKey: "properties.pedro1.details",
    lat: 41.65393,
    lng: -0.90783,
    guests: 4,
    price: "950 EUR",
    priceNumber: 950,
    rating: 4.8,
    availableFrom: "2026-07-01",
    isNew: false,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen"],
    unavailable: [["2026-06-20", "2026-06-24"], ["2026-07-04", "2026-07-10"], ["2026-08-12", "2026-08-18"]]
  },
  {
    id: "pedro2",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro2.name",
    areaKey: "properties.pedro2.area",
    copyKey: "properties.pedro2.copy",
    detailsKey: "properties.pedro2.details",
    lat: 41.65416,
    lng: -0.90756,
    guests: 4,
    price: "980 EUR",
    priceNumber: 980,
    rating: 4.7,
    availableFrom: "2026-07-10",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen", "ac"],
    unavailable: [["2026-06-27", "2026-07-03"], ["2026-07-18", "2026-07-22"], ["2026-08-10", "2026-08-14"]]
  },
  {
    id: "movera0",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera0.name",
    areaKey: "properties.movera0.area",
    copyKey: "properties.movera0.copy",
    detailsKey: "properties.movera0.details",
    lat: 41.64929,
    lng: -0.82209,
    guests: 5,
    price: "870 EUR",
    priceNumber: 870,
    rating: 4.9,
    availableFrom: "2026-08-03",
    isNew: false,
    checked: true,
    depositProtected: true,
    billsIncluded: false,
    amenities: ["wifi", "heating", "kitchen", "terrace"],
    unavailable: [["2026-06-15", "2026-06-21"], ["2026-07-26", "2026-08-02"]]
  },
  {
    id: "movera1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera1.name",
    areaKey: "properties.movera1.area",
    copyKey: "properties.movera1.copy",
    detailsKey: "properties.movera1.details",
    priceNoteKey: "properties.movera1.priceNote",
    lat: 41.64952,
    lng: -0.82182,
    guests: 3,
    price: "1.350 EUR",
    priceNumber: 1350,
    rating: 4.7,
    availableFrom: "2026-07-01",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "heating", "kitchen", "terrace"],
    unavailable: [["2026-06-22", "2026-06-29"], ["2026-08-01", "2026-08-16"]]
  }
];

const addressLocations = {
  pedro: { lat: 41.65393, lng: -0.90783 },
  movera: { lat: 41.64929, lng: -0.82209 }
};

function whatsappLink(text) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;
}
