const CONTACT_EMAIL = "info@ebrostay.com";
const WHATSAPP_NUMBER = "34678715418";

const translations = {
  es: {
    "meta.title": "Ebrostay | Alquileres verificados en Zaragoza",
    "meta.description": "Busca viviendas amuebladas y gestionadas por Ebrostay en Zaragoza. Filtra por fechas, presupuesto, capacidad y tipo de propiedad.",
    "nav.search": "Buscar",
    "nav.how": "Cómo funciona",
    "nav.owners": "Propietarios",
    "nav.contact": "Contacto",
    "nav.cta": "Buscar vivienda",
    "hero.imageAlt": "Apartamento amueblado en Zaragoza",
    "hero.kicker": "Alquileres de media estancia en Zaragoza",
    "hero.title": "Encuentra una vivienda lista para entrar.",
    "hero.copy": "Apartamentos, habitaciones y casas amuebladas con gestión local, disponibilidad clara y soporte antes de llegar.",
    "hero.trust1": "Viviendas verificadas",
    "hero.trust2": "Gestión local",
    "hero.trust3": "Reserva online",
    "search.city": "Ciudad",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Entrada",
    "search.moveOut": "Salida",
    "search.guests": "Personas",
    "search.button": "Buscar",
    "market.kicker": "Búsqueda",
    "market.title": "Viviendas disponibles en Zaragoza",
    "filters.city": "Ciudad",
    "filters.checkIn": "Entrada",
    "filters.checkOut": "Salida",
    "filters.guests": "Personas",
    "filters.type": "Tipo de vivienda",
    "filters.typeAll": "Todos",
    "filters.typeApartment": "Apartamento",
    "filters.typeRoom": "Habitación",
    "filters.typeHome": "Casa",
    "filters.budget": "Presupuesto mensual máximo",
    "filters.anyBudget": "Sin límite",
    "filters.mustHave": "Imprescindible",
    "filters.sort": "Ordenar",
    "filters.sortBest": "Mejor opción",
    "filters.sortPrice": "Precio más bajo",
    "filters.sortNew": "Novedades",
    "filters.apply": "Aplicar filtros",
    "filters.reset": "Reiniciar",
    "filters.show": "Filtros",
    "quick.verified": "Verificadas",
    "quick.bills": "Gastos incluidos",
    "quick.deposit": "Fianza reembolsable",
    "status.all": "Mostrando {count} viviendas gestionadas.",
    "status.matches": "{count} viviendas encontradas.",
    "status.one": "1 vivienda encontrada.",
    "status.none": "No hay viviendas para esos filtros.",
    "status.invalid": "La fecha de salida debe ser posterior a la entrada.",
    "listing.available": "Disponible",
    "listing.unavailable": "No disponible",
    "listing.capacity": "Hasta {guests} personas",
    "listing.price": "{price}/mes",
    "listing.from": "Disponible desde {date}",
    "listing.rating": "{rating} valoración",
    "listing.view": "Ver vivienda",
    "listing.map": "Mapa",
    "listing.favorite": "Guardar",
    "listing.saved": "Guardado",
    "listing.request": "Solicitar",
    "listing.book": "Reservar",
    "badge.checked": "Verificada",
    "badge.deposit": "Fianza reembolsable",
    "badge.bills": "Gastos incluidos",
    "type.apartment": "Apartamento",
    "type.room": "Habitación",
    "type.home": "Casa",
    "amenity.wifi": "wifi",
    "amenity.desk": "mesa de trabajo",
    "amenity.balcony": "balcón",
    "amenity.lift": "ascensor",
    "amenity.ac": "aire acondicionado",
    "amenity.heating": "calefacción",
    "amenity.kitchen": "cocina equipada",
    "amenity.terrace": "terraza",
    "amenity.washer": "lavadora",
    "amenity.dishwasher": "lavavajillas",
    "amenity.tv": "TV",
    "amenity.microwave": "microondas",
    "amenity.oven": "horno",
    "amenity.parking": "parking",
    "spec.bedroom": "1 habitación",
    "spec.bedrooms": "{count} habitaciones",
    "spec.bathroom": "1 baño",
    "spec.bathrooms": "{count} baños",
    "spec.size": "{size} m²",
    "spec.floor": "Planta {floor}",
    "spec.groundFloor": "Planta baja",
    "detail.conditions": "Condiciones",
    "detail.video": "Ver vídeo de la vivienda",
    "cond.minStay": "Estancia mínima",
    "cond.maxStay": "Estancia máxima",
    "cond.month": "1 mes",
    "cond.months": "{count} meses",
    "cond.deposit": "Fianza",
    "cond.upfront": "Renta por adelantado",
    "movein.title": "Coste de entrada",
    "movein.upfront": "Renta por adelantado",
    "movein.deposit": "Fianza",
    "movein.total": "Total para entrar",
    "cond.eur": "{amount} EUR",
    "cond.utilities": "Límite de suministros",
    "cond.eurMonth": "{amount} EUR/mes",
    "cond.energy": "Certificado energético",
    "cond.beds": "Camas",
    "cond.pets": "Mascotas",
    "cond.smoking": "Se permite fumar",
    "cond.couples": "Parejas",
    "cond.selfCheckin": "Autoentrada con lockbox",
    "common.yes": "Sí",
    "common.no": "No",
    "cal.legend": "Los días tachados en rojo no están disponibles.",
    "nav.about": "Nosotros",
    "about.kicker": "Sobre Ebrostay",
    "about.title": "Gestión local de estancias en Zaragoza.",
    "about.copy1": "Ebrostay es un equipo local de Zaragoza que prepara y gestiona viviendas amuebladas para estancias de media duración: profesionales desplazados, estudiantes y familias en transición.",
    "about.copy2": "Nos ocupamos de todo el ciclo: anuncios verificados, entrada con soporte, limpieza, incidencias y comunicación cercana durante toda la estancia.",
    "about.copy3": "¿Quieres ver una vivienda o tienes dudas? Escríbenos a info@ebrostay.com o por WhatsApp y te respondemos en el día.",
    "account.title": "Mi cuenta",
    "bookings.button": "Mi cuenta",
    "bookings.title": "Mis reservas",
    "bookings.copy": "Las estancias confirmadas con tu cuenta aparecen aquí.",
    "bookings.empty": "Todavía no tienes reservas asociadas a tu cuenta. Cuando confirmes una estancia con nosotros, aparecerá aquí.",
    "bookings.error": "No se pudieron cargar tus reservas. Inténtalo de nuevo.",
    "book.title": "Reserva online",
    "book.start": "Entrada",
    "book.end": "Salida",
    "book.months": "Duración",
    "book.rent": "Alquiler",
    "book.payNow": "Total a pagar ahora",
    "book.stay": "Estancia",
    "book.button": "Reservar y pagar",
    "book.note": "Pagas ahora la estancia completa y la fianza para confirmar la reserva. La fianza es reembolsable al finalizar la estancia.",
    "book.loginFirst": "Inicia sesión en la página principal para reservar.",
    "book.unavailable": "Esas fechas no están disponibles.",
    "book.notConfigured": "El pago online aún no está activado. Escríbenos por WhatsApp y confirmamos tu reserva.",
    "book.error": "No se pudo iniciar el pago. Inténtalo de nuevo.",
    "book.redirecting": "Abriendo el pago seguro de Stripe...",
    "book.confirmed": "¡Reserva confirmada! Te hemos enviado un correo con los detalles.",
    "book.cancelled": "Pago cancelado. Tu reserva no se ha realizado.",
    "bookings.paidLabel": "Pagado",
    "bookings.invoice": "Factura",
    "bookings.pdf": "PDF",
    "bookings.receipt": "Recibo",
    "bookings.assignedLabel": "Confirmada",
    "account.loading": "Cargando tu cuenta…",
    "account.signedOutTitle": "Inicia sesión para ver tus reservas.",
    "account.signedOutCopy": "Tus estancias pagadas y asignadas, con sus facturas y recibos, aparecen aquí cuando entras con tu cuenta.",
    "account.sessionTitle": "Sesión y cuenta",
    "account.deactivate": "Desactivar mi cuenta",
    "account.deactivateConfirm": "Tu cuenta se desactivará y no podrás volver a entrar. Conservamos tu historial de reservas. Pulsa otra vez para confirmar.",
    "account.deactivateError": "No se pudo desactivar la cuenta. Inténtalo de nuevo.",
    "account.delete": "Eliminar mi cuenta",
    "account.deleteConfirm": "¿Seguro? Es definitivo. Pulsa otra vez para eliminar.",
    "account.deleteError": "No se pudo eliminar la cuenta. Inténtalo de nuevo.",
    "account.close": "Cerrar",
    "book.minStay": "Estancia mínima: {count} meses",
    "book.loginCta": "Inicia sesión para reservar →",
    "nav.privacy": "Privacidad",
    "admin.addProperty": "Añadir vivienda",
    "admin.addPropertyName": "Nombre de la nueva vivienda:",
    "detail.floorplan": "Plano de la vivienda",
    "detail.floorplanCopy": "Distribución orientativa de la vivienda.",
    "detail.distancesNote": "Tiempos de trayecto aproximados desde la vivienda.",
    "landmark.pilar": "Plaza del Pilar (centro)",
    "landmark.delicias": "Estación Delicias (AVE)",
    "landmark.plaza": "PLAZA (Plataforma Logística)",
    "dist.walk": "A pie",
    "dist.transit": "Transporte público (estimado)",
    "dist.car": "En coche",
    "admin.floorplan": "Plano",
    "admin.makeFloorplan": "Marcar como plano",
    "admin.unmakeFloorplan": "Quitar de planos",
    "dist.placeholder": "Tu trabajo, una dirección, un lugar...",
    "dist.calc": "Calcular distancia",
    "dist.searching": "Buscando dirección…",
    "dist.notFound": "No encontramos esa dirección. Prueba con calle y número.",
    "admin.floorplans": "Planos de la vivienda",
    "admin.addFloorplans": "Añadir planos",
    "admin.noFloorplans": "Todavía no hay planos.",
    "admin.floorplansCopy": "Se muestran en su propia sección del anuncio, separados de las fotos.",
    "admin.guestInfo": "Información para inquilinos",
    "admin.guestInfoCopy": "Wifi, llaves y contacto de emergencia. Solo visible para huéspedes con reserva en esta vivienda.",
    "share.button": "Compartir",
    "share.copied": "Enlace copiado al portapapeles",
    "share.text": "Mira esta vivienda en Ebrostay",
    "nav.menu": "Menú",
    "bookings.viewDetails": "Ver detalles de tu estancia",
    "booking.back": "Volver a mis reservas",
    "booking.kicker": "Tu reserva",
    "booking.notFoundTitle": "No encontramos esta reserva.",
    "booking.notFoundCopy": "Inicia sesión con la cuenta que hizo la reserva y vuelve a intentarlo.",
    "booking.viewProperty": "Ver anuncio de la vivienda",
    "booking.guestInfoTitle": "Información para tu estancia",
    "booking.guestInfoPending": "Te enviaremos los detalles de entrada (wifi, llaves y contacto) antes de tu llegada.",
    "booking.guestInfoHelp": "¿Dudas? Escríbenos a",
    "booking.paidAmount": "Pagado",
    "booking.status": "Estado",
    "booking.reference": "Referencia",
    "guest.wifiName": "Red wifi",
    "guest.wifiPassword": "Contraseña wifi",
    "guest.keyPickup": "Recogida de llaves",
    "guest.checkinTime": "Hora de entrada",
    "guest.checkoutTime": "Hora de salida",
    "guest.emergencyPhone": "Teléfono de emergencia",
    "guest.notes": "Notas",
    "admin.tabProperties": "Propiedades",
    "admin.tabBookings": "Reservas",
    "admin.propListCopy": "Pulsa una vivienda para editar sus textos, fotos, dirección y disponibilidad.",
    "admin.editProperty": "Editar",
    "admin.confirmedBookings": "Reservas confirmadas",
    "admin.confirmedCopy": "Reservas pagadas a través de Stripe, con fecha de confirmación, datos del huésped y factura.",
    "admin.assignedStays": "Estancias asignadas",
    "admin.assignedCopy": "Estancias asignadas manualmente a un huésped desde el editor de cada vivienda.",
    "admin.noBookings": "Todavía no hay reservas.",
    "admin.backToPanel": "Volver al panel",
    "admin.th.confirmed": "Confirmada",
    "admin.th.property": "Vivienda",
    "admin.th.checkin": "Entrada",
    "admin.th.checkout": "Salida",
    "admin.th.months": "Meses",
    "admin.th.amount": "Importe",
    "admin.th.name": "Nombre",
    "admin.th.email": "Email",
    "admin.th.invoice": "Factura",
    "admin.field.addressFull": "Dirección (calle y número)",
    "admin.addressHint": "La dirección se muestra en el anuncio y en la factura; las coordenadas se calculan automáticamente al guardar.",
    "auth.or": "o",
    "auth.signupTitle": "Crea tu cuenta",
    "auth.signupCopy": "Crea tu cuenta para reservar online y gestionar tus estancias.",
    "auth.forgot": "¿Has olvidado tu contraseña?",
    "auth.resetTitle": "Restablecer contraseña",
    "auth.resetCopy": "Escribe tu email y te enviaremos un enlace para crear una nueva contraseña.",
    "auth.resetSend": "Enviar enlace",
    "auth.resetError": "No se pudo enviar el correo. Revisa el email e inténtalo de nuevo.",
    "auth.recoverTitle": "Elige una nueva contraseña",
    "auth.recoverCopy": "Escribe la nueva contraseña para tu cuenta.",
    "auth.recoverSave": "Guardar contraseña",
    "auth.recoverError": "No se pudo guardar la contraseña. Inténtalo de nuevo.",
    "auth.successEmailTitle": "Revisa tu correo",
    "auth.successConfirmCopy": "Hemos enviado un enlace de confirmación a {email}. Ábrelo para activar tu cuenta y después inicia sesión.",
    "auth.successResetCopy": "Hemos enviado un enlace a {email} para restablecer tu contraseña.",
    "auth.successRecoverTitle": "Contraseña actualizada",
    "auth.successRecoverCopy": "Ya puedes usar tu nueva contraseña.",
    "auth.google": "Continuar con Google",
    "auth.microsoft": "Continuar con Outlook",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "Universidad - Pedro II el Católico",
    "properties.pedro1.copy": "Piso amueblado en Pedro II el Católico 3, preparado para estancias de media duración en Zaragoza.",
    "properties.pedro1.details": "Primero izquierda en una ubicación urbana y bien comunicada, con cocina equipada, zona de trabajo y gestión local Ebrostay.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "Universidad - Pedro II el Católico",
    "properties.pedro2.copy": "Segundo izquierda en el mismo edificio, una opción práctica para profesionales, estudiantes o traslados temporales.",
    "properties.pedro2.details": "Vivienda amueblada con distribución funcional, wifi, calefacción y soporte local para llegada y estancia.",
    "properties.movera0.name": "Movera 7 - Planta Baja",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Piso en planta baja en Movera 7, pensado para estancias tranquilas con acceso cómodo.",
    "properties.movera0.details": "Opción de planta baja con cocina equipada, buena capacidad y gestión cercana para incidencias o necesidades durante la estancia.",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Piso de 3 habitaciones privadas en Movera 7, ideal para equipos de empresa, técnicos y estancias por proyecto.",
    "properties.movera1.details": "Tres dormitorios privados con salón, comedor y cocina equipada compartidos, baño completo y terraza. Gastos incluidos con suministros limitados a 50 EUR por habitación, autoentrada con lockbox y soporte 24/7. Piso completo o por habitaciones.",
    "properties.movera1.priceNote": "o 450 EUR/habitación",
    "map.title": "Mapa de viviendas",
    "map.copy": "Cada pin muestra el precio mensual de una vivienda. Toca un pin para resaltar la vivienda o usa los botones para ir a cada dirección.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "Cómo funciona",
    "how.title": "Busca, reserva y llega con todo claro.",
    "how.step1.title": "Filtra",
    "how.step1.copy": "Elige fechas, presupuesto, capacidad y comodidades para reducir la búsqueda.",
    "how.step2.title": "Revisa",
    "how.step2.copy": "Compara viviendas verificadas, detalles, ubicación, precio mensual y disponibilidad.",
    "how.step3.title": "Reserva",
    "how.step3.copy": "Reserva y paga online de forma segura: la estancia completa más la fianza reembolsable. Confirmación y factura al momento.",
    "owners.kicker": "Para propietarios",
    "owners.title": "Publica y opera tu vivienda con ayuda local.",
    "owners.copy": "Ebrostay prepara anuncios, coordina entradas, limpiezas, incidencias y comunicación con huéspedes para que tu propiedad funcione mejor sin absorber tu día.",
    "contact.kicker": "Contacto",
    "contact.title": "Cuéntanos qué necesitas.",
    "contact.copy": "Cuéntanos fechas, personas y presupuesto, o pide la gestión de tu vivienda. Te respondemos lo antes posible.",
    "contact.whatsapp": "Escríbenos por WhatsApp",
    "form.name": "Nombre",
    "form.email": "Email",
    "form.property": "Propiedad o zona",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Mensaje",
    "form.messagePlaceholder": "Fechas, personas, presupuesto o gestión de propiedad...",
    "form.button": "Enviar mensaje",
    "form.note": "Tu mensaje nos llega directamente; te respondemos por email.",
    "email.subject": "Consulta Ebrostay de",
    "email.defaultMessage": "Quiero saber más sobre una vivienda o gestión de propiedad con Ebrostay.",
    "email.propertyFallback": "Sin especificar",
    "detail.back": "Volver a resultados",
    "detail.about": "Sobre esta vivienda",
    "detail.amenities": "Comodidades",
    "detail.location": "Ubicación",
    "detail.locationCopy": "Ubicación aproximada de la vivienda en Zaragoza.",
    "detail.blocked": "Disponibilidad",
    "detail.blockedCopy": "Estas fechas no están disponibles ahora mismo. Para otras fechas, envía tu solicitud.",
    "detail.requestTitle": "¿Te interesa esta vivienda?",
    "detail.requestCopy": "Escríbenos y confirmamos disponibilidad, condiciones y siguiente paso.",
    "detail.emailButton": "Solicitar por email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "O usa el formulario de contacto",
    "whatsapp.message": "Hola Ebrostay, me interesa {property}. ¿Podéis confirmar disponibilidad?",
    "whatsapp.general": "Hola Ebrostay, quiero información sobre una vivienda o gestión de propiedad.",
    "form.sent": "¡Gracias! Hemos recibido tu mensaje y te responderemos pronto.",
    "form.errorSend": "No se pudo enviar. Inténtalo de nuevo o escríbenos por WhatsApp.",
    "auth.login": "Entrar",
    "auth.logout": "Salir",
    "auth.title": "Accede a tu cuenta",
    "auth.copy": "Accede para reservar online, guardar favoritas y consultar tus reservas y facturas.",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.signin": "Iniciar sesión",
    "auth.signup": "Crear cuenta",
    "auth.close": "Cerrar",
    "auth.checkEmail": "Revisa tu correo para confirmar la cuenta.",
    "auth.error": "No se pudo iniciar sesión. Revisa los datos.",
    "auth.signupError": "No se pudo crear la cuenta. Revisa los datos.",
    "auth.admin": "Administración",
    "admin.title": "Panel de administración",
    "admin.copy": "Gestiona anuncios, fotos, precios y disponibilidad. Los cambios se publican al momento.",
    "admin.signinFirst": "Inicia sesión con tu cuenta de administración.",
    "admin.notAdmin": "Tu cuenta no tiene permisos de administración.",
    "admin.notConfigured": "Supabase no está configurado todavía. Completa supabase-config.js.",
    "admin.blocks": "Periodos reservados",
    "admin.noBlocks": "Sin periodos reservados.",
    "admin.from": "Desde",
    "admin.to": "Hasta",
    "admin.add": "Añadir periodo",
    "admin.delete": "Eliminar",
    "admin.availableFrom": "Disponible desde",
    "admin.save": "Guardar",
    "admin.saved": "Guardado.",
    "admin.error": "No se pudo guardar. Inténtalo de nuevo.",
    "admin.back": "Volver al sitio",
    "admin.editDetails": "Editar detalles del anuncio",
    "admin.photos": "Fotos",
    "admin.addPhotos": "Subir fotos",
    "admin.uploading": "Subiendo fotos...",
    "admin.noPhotos": "Sin fotos todavía. Las viviendas sin fotos muestran una imagen genérica.",
    "admin.cover": "Portada",
    "admin.makeCover": "Hacer portada",
    "admin.field.name": "Nombre del anuncio",
    "admin.field.areaEs": "Zona (español)",
    "admin.field.areaEn": "Zona (inglés)",
    "admin.field.copyEs": "Descripción corta (español)",
    "admin.field.copyEn": "Descripción corta (inglés)",
    "admin.field.detailsEs": "Descripción completa (español)",
    "admin.field.detailsEn": "Descripción completa (inglés)",
    "admin.field.priceLabel": "Precio mostrado (ej. 950 EUR)",
    "admin.field.priceNumber": "Precio numérico (para filtros)",
    "admin.field.priceNoteEs": "Nota de precio (español, opcional)",
    "admin.field.priceNoteEn": "Nota de precio (inglés, opcional)",
    "admin.field.guests": "Capacidad (personas)",
    "admin.field.rating": "Valoración (0-5)",
    "admin.field.type": "Tipo de vivienda",
    "admin.field.addressKey": "Grupo de dirección (pedro, movera...)",
    "admin.field.lat": "Latitud",
    "admin.field.lng": "Longitud",
    "admin.field.city": "Ciudad",
    "admin.field.amenities": "Comodidades",
    "admin.flag.isNew": "Novedad",
    "admin.flag.checked": "Verificada",
    "admin.flag.deposit": "Depósito protegido",
    "admin.flag.bills": "Gastos incluidos",
    "admin.flag.published": "Publicada en la web",
    "admin.published": "Publicada",
    "admin.unpublished": "No publicada",
    "admin.guestsUnit": "personas",
    "admin.availability": "Disponibilidad",
    "admin.saveChanges": "Guardar cambios",
    "admin.section.basic": "Información básica",
    "admin.section.price": "Precio",
    "admin.section.textsEs": "Textos en español",
    "admin.section.textsEn": "Textos en inglés",
    "admin.section.location": "Ubicación",
    "admin.section.status": "Estado",
    "admin.field.address": "Dirección",
    "admin.geocodePlaceholder": "Calle y número, ciudad (ej. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Buscar coordenadas",
    "admin.geocodeSearching": "Buscando la dirección...",
    "admin.geocodeNone": "No se encontró la dirección. Prueba con más detalle.",
    "admin.geocodeFound": "Coordenadas rellenadas para:",
    "admin.geocodeError": "No se pudo buscar ahora mismo. Inténtalo de nuevo.",
    "admin.geocodeHint": "Escribe la dirección y pulsa Buscar: la latitud y longitud (la chincheta del mapa) se rellenan solas. Después pulsa Guardar cambios.",
    "admin.field.bedrooms": "Habitaciones",
    "admin.field.bathrooms": "Baños",
    "admin.field.size": "Superficie (m²)",
    "admin.field.floor": "Planta (0 = baja)",
    "admin.section.conditions": "Condiciones",
    "admin.field.minStay": "Estancia mínima (meses)",
    "admin.field.maxStay": "Estancia máxima (meses)",
    "admin.field.deposit": "Fianza (EUR)",
    "admin.field.upfront": "Renta por adelantado (EUR)",
    "admin.field.utilitiesCap": "Límite de suministros (EUR/mes)",
    "admin.field.energy": "Certificado energético",
    "admin.field.video": "Enlace de vídeo (opcional)",
    "admin.field.bedsEs": "Camas (español, ej. 2 dobles y 1 individual)",
    "admin.field.bedsEn": "Camas (inglés)",
    "admin.energyNone": "Sin especificar",
    "admin.flag.pets": "Mascotas permitidas",
    "admin.flag.smoking": "Se permite fumar",
    "admin.flag.couples": "Parejas permitidas",
    "admin.flag.selfCheckin": "Autoentrada (lockbox)",
    "admin.field.guestEmail": "Email del huésped (opcional)",
    "admin.guestNotFound": "No existe ningún usuario registrado con ese email.",
    "admin.guest": "Huésped",
    "admin.users": "Usuarios",
    "admin.usersCopy": "Cuentas registradas. Las cuentas desactivadas se pueden eliminar definitivamente (las reservas pagadas se conservan).",
    "admin.deactivatedChip": "Desactivada",
    "admin.adminChip": "Admin",
    "admin.bookingsCount": "Reservas: {count}",
    "admin.deleteUser": "Eliminar",
    "admin.deleteUserConfirm": "¿Seguro? Pulsa otra vez",
    "admin.userDeleted": "Usuario eliminado."
  },
  en: {
    "meta.title": "Ebrostay | Verified rentals in Zaragoza",
    "meta.description": "Search furnished homes managed by Ebrostay in Zaragoza. Filter by dates, budget, capacity, and property type.",
    "nav.search": "Search",
    "nav.how": "How it works",
    "nav.owners": "Owners",
    "nav.contact": "Contact",
    "nav.cta": "List a home",
    "hero.imageAlt": "Furnished apartment in Zaragoza",
    "hero.kicker": "Medium-stay rentals in Zaragoza",
    "hero.title": "Find a home ready to move into.",
    "hero.copy": "Furnished apartments, rooms, and homes with local management, clear availability, and support before arrival.",
    "hero.trust1": "Verified homes",
    "hero.trust2": "Local management",
    "hero.trust3": "Online booking",
    "search.city": "City",
    "search.cityPlaceholder": "Zaragoza",
    "search.moveIn": "Move-in",
    "search.moveOut": "Move-out",
    "search.guests": "People",
    "search.button": "Search",
    "market.kicker": "Search",
    "market.title": "Available homes in Zaragoza",
    "filters.city": "City",
    "filters.checkIn": "Move-in",
    "filters.checkOut": "Move-out",
    "filters.guests": "People",
    "filters.type": "Home type",
    "filters.typeAll": "All",
    "filters.typeApartment": "Apartment",
    "filters.typeRoom": "Room",
    "filters.typeHome": "House",
    "filters.budget": "Maximum monthly budget",
    "filters.anyBudget": "No limit",
    "filters.mustHave": "Must-have",
    "filters.sort": "Sort",
    "filters.sortBest": "Best match",
    "filters.sortPrice": "Lowest price",
    "filters.sortNew": "New arrivals",
    "filters.apply": "Apply filters",
    "filters.reset": "Reset",
    "filters.show": "Filters",
    "quick.verified": "Verified",
    "quick.bills": "Bills included",
    "quick.deposit": "Refundable deposit",
    "status.all": "Showing {count} managed homes.",
    "status.matches": "{count} homes found.",
    "status.one": "1 home found.",
    "status.none": "No homes match those filters.",
    "status.invalid": "Move-out must be after move-in.",
    "listing.available": "Available",
    "listing.unavailable": "Unavailable",
    "listing.capacity": "Up to {guests} people",
    "listing.price": "{price}/month",
    "listing.from": "Available from {date}",
    "listing.rating": "{rating} rating",
    "listing.view": "View home",
    "listing.map": "Map",
    "listing.favorite": "Save",
    "listing.saved": "Saved",
    "listing.request": "Request",
    "listing.book": "Book",
    "badge.checked": "Verified",
    "badge.deposit": "Refundable deposit",
    "badge.bills": "Bills included",
    "type.apartment": "Apartment",
    "type.room": "Room",
    "type.home": "House",
    "amenity.wifi": "wifi",
    "amenity.desk": "desk",
    "amenity.balcony": "balcony",
    "amenity.lift": "lift",
    "amenity.ac": "air conditioning",
    "amenity.heating": "heating",
    "amenity.kitchen": "equipped kitchen",
    "amenity.terrace": "terrace",
    "amenity.washer": "washing machine",
    "amenity.dishwasher": "dishwasher",
    "amenity.tv": "TV",
    "amenity.microwave": "microwave",
    "amenity.oven": "oven",
    "amenity.parking": "parking",
    "spec.bedroom": "1 bedroom",
    "spec.bedrooms": "{count} bedrooms",
    "spec.bathroom": "1 bathroom",
    "spec.bathrooms": "{count} bathrooms",
    "spec.size": "{size} m²",
    "spec.floor": "Floor {floor}",
    "spec.groundFloor": "Ground floor",
    "detail.conditions": "Conditions",
    "detail.video": "Watch the video tour",
    "cond.minStay": "Minimum stay",
    "cond.maxStay": "Maximum stay",
    "cond.month": "1 month",
    "cond.months": "{count} months",
    "cond.deposit": "Deposit",
    "cond.upfront": "Upfront rent",
    "movein.title": "Move-in cost",
    "movein.upfront": "Upfront rent",
    "movein.deposit": "Deposit",
    "movein.total": "Total to move in",
    "cond.eur": "{amount} EUR",
    "cond.utilities": "Utilities cap",
    "cond.eurMonth": "{amount} EUR/month",
    "cond.energy": "Energy certificate",
    "cond.beds": "Beds",
    "cond.pets": "Pets",
    "cond.smoking": "Smoking allowed",
    "cond.couples": "Couples",
    "cond.selfCheckin": "Self check-in with lockbox",
    "common.yes": "Yes",
    "common.no": "No",
    "cal.legend": "Days crossed out in red are not available.",
    "nav.about": "About",
    "about.kicker": "About Ebrostay",
    "about.title": "Local mid-stay management in Zaragoza.",
    "about.copy1": "Ebrostay is a local Zaragoza team that prepares and manages furnished homes for medium-term stays: relocated professionals, students, and families in transition.",
    "about.copy2": "We handle the whole cycle: verified listings, supported check-in, cleaning, incidents, and close communication throughout the stay.",
    "about.copy3": "Want to visit a home or have questions? Write to info@ebrostay.com or message us on WhatsApp and we reply the same day.",
    "account.title": "My account",
    "bookings.button": "My account",
    "bookings.title": "My bookings",
    "bookings.copy": "Stays confirmed with your account appear here.",
    "bookings.empty": "You have no bookings linked to your account yet. Once you confirm a stay with us, it will appear here.",
    "bookings.error": "Could not load your bookings. Try again.",
    "book.title": "Book online",
    "book.start": "Check-in",
    "book.end": "Check-out",
    "book.months": "Duration",
    "book.rent": "Rent",
    "book.payNow": "Total due now",
    "book.stay": "Stay",
    "book.button": "Book and pay",
    "book.note": "You pay the full stay plus the deposit now to confirm the booking. The deposit is refundable at the end of the stay.",
    "book.loginFirst": "Sign in on the home page to book.",
    "book.unavailable": "Those dates are not available.",
    "book.notConfigured": "Online payment is not enabled yet. Message us on WhatsApp to confirm your booking.",
    "book.error": "Could not start the payment. Try again.",
    "book.redirecting": "Opening Stripe secure checkout...",
    "book.confirmed": "Booking confirmed! We sent you an email with the details.",
    "book.cancelled": "Payment cancelled. Your booking was not made.",
    "bookings.paidLabel": "Paid",
    "bookings.invoice": "Invoice",
    "bookings.pdf": "PDF",
    "bookings.receipt": "Receipt",
    "bookings.assignedLabel": "Confirmed",
    "account.loading": "Loading your account…",
    "account.signedOutTitle": "Sign in to see your bookings.",
    "account.signedOutCopy": "Your paid and assigned stays, with their invoices and receipts, appear here once you sign in.",
    "account.sessionTitle": "Session & account",
    "account.deactivate": "Deactivate my account",
    "account.deactivateConfirm": "Your account will be deactivated and you will not be able to sign in again. We keep your booking history. Press again to confirm.",
    "account.deactivateError": "Could not deactivate the account. Try again.",
    "account.delete": "Delete my account",
    "account.deleteConfirm": "Sure? This is permanent. Press again to delete.",
    "account.deleteError": "Could not delete the account. Try again.",
    "account.close": "Close",
    "book.minStay": "Minimum stay: {count} months",
    "book.loginCta": "Sign in to book →",
    "nav.privacy": "Privacy",
    "admin.addProperty": "Add property",
    "admin.addPropertyName": "Name of the new property:",
    "detail.floorplan": "Floor plan",
    "detail.floorplanCopy": "Approximate layout of the home.",
    "detail.distancesNote": "Approximate travel times from the home.",
    "landmark.pilar": "Plaza del Pilar (city centre)",
    "landmark.delicias": "Delicias station (AVE)",
    "landmark.plaza": "PLAZA (Logistics Platform)",
    "dist.walk": "Walking",
    "dist.transit": "Public transport (estimated)",
    "dist.car": "By car",
    "admin.floorplan": "Floor plan",
    "admin.makeFloorplan": "Mark as floor plan",
    "admin.unmakeFloorplan": "Unmark floor plan",
    "dist.placeholder": "Your workplace, an address, a place...",
    "dist.calc": "Calculate distance",
    "dist.searching": "Looking up the address…",
    "dist.notFound": "We could not find that address. Try street and number.",
    "admin.floorplans": "Floor plans",
    "admin.addFloorplans": "Add floor plans",
    "admin.noFloorplans": "No floor plans yet.",
    "admin.floorplansCopy": "Shown in their own section of the listing, separate from the photos.",
    "admin.guestInfo": "Tenant information",
    "admin.guestInfoCopy": "Wifi, keys and emergency contact. Only visible to guests with a booking for this home.",
    "share.button": "Share",
    "share.copied": "Link copied to clipboard",
    "share.text": "Check out this home on Ebrostay",
    "nav.menu": "Menu",
    "bookings.viewDetails": "View your stay details",
    "booking.back": "Back to my bookings",
    "booking.kicker": "Your booking",
    "booking.notFoundTitle": "We could not find this booking.",
    "booking.notFoundCopy": "Sign in with the account that made the booking and try again.",
    "booking.viewProperty": "View the property listing",
    "booking.guestInfoTitle": "Information for your stay",
    "booking.guestInfoPending": "We will send you the arrival details (wifi, keys and contact) before your check-in.",
    "booking.guestInfoHelp": "Questions? Write to us at",
    "booking.paidAmount": "Paid",
    "booking.status": "Status",
    "booking.reference": "Reference",
    "guest.wifiName": "Wifi network",
    "guest.wifiPassword": "Wifi password",
    "guest.keyPickup": "Key pickup",
    "guest.checkinTime": "Check-in time",
    "guest.checkoutTime": "Check-out time",
    "guest.emergencyPhone": "Emergency phone",
    "guest.notes": "Notes",
    "admin.tabProperties": "Properties",
    "admin.tabBookings": "Bookings",
    "admin.propListCopy": "Click a property to edit its texts, photos, address and availability.",
    "admin.editProperty": "Edit",
    "admin.confirmedBookings": "Confirmed bookings",
    "admin.confirmedCopy": "Bookings paid via Stripe, with confirmation timestamp, guest details and invoice.",
    "admin.assignedStays": "Assigned stays",
    "admin.assignedCopy": "Stays assigned manually to a guest from each property editor.",
    "admin.noBookings": "No bookings yet.",
    "admin.backToPanel": "Back to the panel",
    "admin.th.confirmed": "Confirmed",
    "admin.th.property": "Property",
    "admin.th.checkin": "Check-in",
    "admin.th.checkout": "Check-out",
    "admin.th.months": "Months",
    "admin.th.amount": "Amount",
    "admin.th.name": "Name",
    "admin.th.email": "Email",
    "admin.th.invoice": "Invoice",
    "admin.field.addressFull": "Address (street and number)",
    "admin.addressHint": "The address appears on the listing and the invoice; coordinates are derived automatically on save.",
    "auth.or": "or",
    "auth.signupTitle": "Create your account",
    "auth.signupCopy": "Create your account to book online and manage your stays.",
    "auth.forgot": "Forgot your password?",
    "auth.resetTitle": "Reset password",
    "auth.resetCopy": "Enter your email and we will send you a link to create a new password.",
    "auth.resetSend": "Send link",
    "auth.resetError": "Could not send the email. Check the address and try again.",
    "auth.recoverTitle": "Choose a new password",
    "auth.recoverCopy": "Enter the new password for your account.",
    "auth.recoverSave": "Save password",
    "auth.recoverError": "Could not save the password. Try again.",
    "auth.successEmailTitle": "Check your email",
    "auth.successConfirmCopy": "We sent a confirmation link to {email}. Open it to activate your account, then sign in.",
    "auth.successResetCopy": "We sent a link to {email} to reset your password.",
    "auth.successRecoverTitle": "Password updated",
    "auth.successRecoverCopy": "You can use your new password now.",
    "auth.google": "Continue with Google",
    "auth.microsoft": "Continue with Outlook",
    "properties.pedro1.name": "Pedro II el Católico 3 - 1 IZQ",
    "properties.pedro1.area": "University - Pedro II el Católico",
    "properties.pedro1.copy": "Furnished flat at Pedro II el Católico 3, prepared for medium-stay rentals in Zaragoza.",
    "properties.pedro1.details": "First-floor left flat in a connected urban location, with equipped kitchen, work area, and local Ebrostay management.",
    "properties.pedro2.name": "Pedro II el Católico 3 - 2 IZQ",
    "properties.pedro2.area": "University - Pedro II el Católico",
    "properties.pedro2.copy": "Second-floor left flat in the same building, practical for professionals, students, or temporary relocations.",
    "properties.pedro2.details": "Furnished home with functional layout, wifi, heating, and local support for arrival and stay.",
    "properties.movera0.name": "Movera 7 - Planta Baja",
    "properties.movera0.area": "Movera",
    "properties.movera0.copy": "Ground-floor flat at Movera 7, designed for calmer stays with easy access.",
    "properties.movera0.details": "Ground-floor option with equipped kitchen, good capacity, and local management for issues or needs during the stay.",
    "properties.movera1.name": "Movera 7 - Primera Planta",
    "properties.movera1.area": "Movera",
    "properties.movera1.copy": "Three private bedrooms at Movera 7, ideal for company teams, technicians, and project stays.",
    "properties.movera1.details": "Three private bedrooms with shared living, dining, and equipped kitchen, full bathroom, and terrace. Expenses included with utilities capped at 50 EUR per room, self check-in by lockbox, and 24/7 support. Whole flat or room by room.",
    "properties.movera1.priceNote": "or 450 EUR/room",
    "map.title": "Homes map",
    "map.copy": "Each pin shows a home's monthly price. Tap a pin to highlight the home or use the buttons to jump to each address.",
    "map.pedro": "Pedro II el Católico 3",
    "map.movera": "Movera 7",
    "how.kicker": "How it works",
    "how.title": "Search, book, and arrive with everything clear.",
    "how.step1.title": "Filter",
    "how.step1.copy": "Choose dates, budget, capacity, and amenities to narrow the search.",
    "how.step2.title": "Review",
    "how.step2.copy": "Compare verified homes, details, location, monthly price, and availability.",
    "how.step3.title": "Book",
    "how.step3.copy": "Book and pay online securely: the full stay plus the refundable deposit. Instant confirmation and invoice.",
    "owners.kicker": "For owners",
    "owners.title": "List and operate your home with local help.",
    "owners.copy": "Ebrostay prepares listings, coordinates arrivals, cleaning, issues, and guest communication so your property works better without taking over your day.",
    "contact.kicker": "Contact",
    "contact.title": "Tell us what you need.",
    "contact.copy": "Tell us your dates, group size and budget, or ask about property management. We reply as soon as possible.",
    "contact.whatsapp": "Message us on WhatsApp",
    "form.name": "Name",
    "form.email": "Email",
    "form.property": "Property or area",
    "form.propertyPlaceholder": "Pedro II el Católico 3, Movera 7...",
    "form.message": "Message",
    "form.messagePlaceholder": "Dates, people, budget, or property management...",
    "form.button": "Send message",
    "form.note": "Your message reaches us directly; we reply by email.",
    "email.subject": "Ebrostay inquiry from",
    "email.defaultMessage": "I would like to know more about a home or property management with Ebrostay.",
    "email.propertyFallback": "Not specified",
    "detail.back": "Back to results",
    "detail.about": "About this home",
    "detail.amenities": "Amenities",
    "detail.location": "Location",
    "detail.locationCopy": "Approximate location of the home in Zaragoza.",
    "detail.blocked": "Availability",
    "detail.blockedCopy": "These dates are currently unavailable. For other dates, send your request.",
    "detail.requestTitle": "Interested in this home?",
    "detail.requestCopy": "Write to us and we confirm availability, terms, and the next step.",
    "detail.emailButton": "Request by email",
    "detail.whatsapp": "WhatsApp",
    "detail.formLink": "Or use the contact form",
    "whatsapp.message": "Hello Ebrostay, I am interested in {property}. Could you confirm availability?",
    "whatsapp.general": "Hello Ebrostay, I would like information about a home or property management.",
    "form.sent": "Thank you! We received your message and will reply soon.",
    "form.errorSend": "Could not send. Try again or message us on WhatsApp.",
    "auth.login": "Sign in",
    "auth.logout": "Sign out",
    "auth.title": "Access your account",
    "auth.copy": "Sign in to book online, save favourites, and see your bookings and invoices.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signin": "Sign in",
    "auth.signup": "Create account",
    "auth.close": "Close",
    "auth.checkEmail": "Check your email to confirm your account.",
    "auth.error": "Could not sign in. Check your details.",
    "auth.signupError": "Could not create the account. Check your details.",
    "auth.admin": "Admin",
    "admin.title": "Admin panel",
    "admin.copy": "Manage listings, photos, prices, and availability. Changes go live immediately.",
    "admin.signinFirst": "Sign in with your admin account.",
    "admin.notAdmin": "Your account does not have admin permissions.",
    "admin.notConfigured": "Supabase is not configured yet. Fill in supabase-config.js.",
    "admin.blocks": "Booked periods",
    "admin.noBlocks": "No booked periods.",
    "admin.from": "From",
    "admin.to": "To",
    "admin.add": "Add period",
    "admin.delete": "Delete",
    "admin.availableFrom": "Available from",
    "admin.save": "Save",
    "admin.saved": "Saved.",
    "admin.error": "Could not save. Try again.",
    "admin.back": "Back to site",
    "admin.editDetails": "Edit listing details",
    "admin.photos": "Photos",
    "admin.addPhotos": "Upload photos",
    "admin.uploading": "Uploading photos...",
    "admin.noPhotos": "No photos yet. Homes without photos show a generic image.",
    "admin.cover": "Cover",
    "admin.makeCover": "Make cover",
    "admin.field.name": "Listing name",
    "admin.field.areaEs": "Area (Spanish)",
    "admin.field.areaEn": "Area (English)",
    "admin.field.copyEs": "Short description (Spanish)",
    "admin.field.copyEn": "Short description (English)",
    "admin.field.detailsEs": "Full description (Spanish)",
    "admin.field.detailsEn": "Full description (English)",
    "admin.field.priceLabel": "Displayed price (e.g. 950 EUR)",
    "admin.field.priceNumber": "Numeric price (for filters)",
    "admin.field.priceNoteEs": "Price note (Spanish, optional)",
    "admin.field.priceNoteEn": "Price note (English, optional)",
    "admin.field.guests": "Capacity (people)",
    "admin.field.rating": "Rating (0-5)",
    "admin.field.type": "Home type",
    "admin.field.addressKey": "Address group (pedro, movera...)",
    "admin.field.lat": "Latitude",
    "admin.field.lng": "Longitude",
    "admin.field.city": "City",
    "admin.field.amenities": "Amenities",
    "admin.flag.isNew": "New arrival",
    "admin.flag.checked": "Verified",
    "admin.flag.deposit": "Deposit protected",
    "admin.flag.bills": "Bills included",
    "admin.flag.published": "Published on the website",
    "admin.published": "Published",
    "admin.unpublished": "Not published",
    "admin.guestsUnit": "guests",
    "admin.availability": "Availability",
    "admin.saveChanges": "Save changes",
    "admin.section.basic": "Basic information",
    "admin.section.price": "Price",
    "admin.section.textsEs": "Spanish texts",
    "admin.section.textsEn": "English texts",
    "admin.section.location": "Location",
    "admin.section.status": "Status",
    "admin.field.address": "Address",
    "admin.geocodePlaceholder": "Street and number, city (e.g. Calle Movera 7, Zaragoza)",
    "admin.geocodeFind": "Find coordinates",
    "admin.geocodeSearching": "Searching for the address...",
    "admin.geocodeNone": "Address not found. Try adding more detail.",
    "admin.geocodeFound": "Coordinates filled in for:",
    "admin.geocodeError": "Could not search right now. Try again.",
    "admin.geocodeHint": "Type the address and press Find: latitude and longitude (the map pin) are filled in automatically. Then press Save changes.",
    "admin.field.bedrooms": "Bedrooms",
    "admin.field.bathrooms": "Bathrooms",
    "admin.field.size": "Size (m²)",
    "admin.field.floor": "Floor (0 = ground)",
    "admin.section.conditions": "Conditions",
    "admin.field.minStay": "Minimum stay (months)",
    "admin.field.maxStay": "Maximum stay (months)",
    "admin.field.deposit": "Deposit (EUR)",
    "admin.field.upfront": "Upfront rent (EUR)",
    "admin.field.utilitiesCap": "Utilities cap (EUR/month)",
    "admin.field.energy": "Energy certificate",
    "admin.field.video": "Video link (optional)",
    "admin.field.bedsEs": "Beds (Spanish, e.g. 2 dobles y 1 individual)",
    "admin.field.bedsEn": "Beds (English)",
    "admin.energyNone": "Not specified",
    "admin.flag.pets": "Pets allowed",
    "admin.flag.smoking": "Smoking allowed",
    "admin.flag.couples": "Couples allowed",
    "admin.flag.selfCheckin": "Self check-in (lockbox)",
    "admin.field.guestEmail": "Guest email (optional)",
    "admin.guestNotFound": "No registered user with that email.",
    "admin.guest": "Guest",
    "admin.users": "Users",
    "admin.usersCopy": "Registered accounts. Deactivated accounts can be deleted permanently (paid bookings are kept).",
    "admin.deactivatedChip": "Deactivated",
    "admin.adminChip": "Admin",
    "admin.bookingsCount": "Bookings: {count}",
    "admin.deleteUser": "Delete",
    "admin.deleteUserConfirm": "Sure? Press again",
    "admin.userDeleted": "User deleted."
  }
};

const properties = [
  {
    id: "pedro1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro1.name",
    areaKey: "properties.pedro1.area",
    copyKey: "properties.pedro1.copy",
    detailsKey: "properties.pedro1.details",
    lat: 41.65393,
    lng: -0.90783,
    guests: 4,
    price: "950 EUR",
    priceNumber: 950,
    rating: 4.8,
    floorNumber: 1,
    availableFrom: "2026-07-01",
    isNew: false,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen"],
    unavailable: [["2026-06-20", "2026-06-24"], ["2026-07-04", "2026-07-10"], ["2026-08-12", "2026-08-18"]]
  },
  {
    id: "pedro2",
    city: "zaragoza",
    type: "apartment",
    addressKey: "pedro",
    nameKey: "properties.pedro2.name",
    areaKey: "properties.pedro2.area",
    copyKey: "properties.pedro2.copy",
    detailsKey: "properties.pedro2.details",
    lat: 41.65416,
    lng: -0.90756,
    guests: 4,
    price: "980 EUR",
    priceNumber: 980,
    rating: 4.7,
    floorNumber: 2,
    availableFrom: "2026-07-10",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "lift", "heating", "kitchen", "ac"],
    unavailable: [["2026-06-27", "2026-07-03"], ["2026-07-18", "2026-07-22"], ["2026-08-10", "2026-08-14"]]
  },
  {
    id: "movera0",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera0.name",
    areaKey: "properties.movera0.area",
    copyKey: "properties.movera0.copy",
    detailsKey: "properties.movera0.details",
    lat: 41.64929,
    lng: -0.82209,
    guests: 5,
    price: "870 EUR",
    priceNumber: 870,
    rating: 4.9,
    floorNumber: 0,
    availableFrom: "2026-08-03",
    isNew: false,
    checked: true,
    depositProtected: true,
    billsIncluded: false,
    amenities: ["wifi", "heating", "kitchen", "terrace"],
    unavailable: [["2026-06-15", "2026-06-21"], ["2026-07-26", "2026-08-02"]]
  },
  {
    id: "movera1",
    city: "zaragoza",
    type: "apartment",
    addressKey: "movera",
    nameKey: "properties.movera1.name",
    areaKey: "properties.movera1.area",
    copyKey: "properties.movera1.copy",
    detailsKey: "properties.movera1.details",
    priceNoteKey: "properties.movera1.priceNote",
    lat: 41.64952,
    lng: -0.82182,
    guests: 3,
    price: "1.350 EUR",
    priceNumber: 1350,
    rating: 4.7,
    floorNumber: 1,
    bedrooms: 3,
    bathrooms: 1,
    utilitiesCapEur: 50,
    selfCheckin: true,
    minStayMonths: 1,
    availableFrom: "2026-07-01",
    isNew: true,
    checked: true,
    depositProtected: true,
    billsIncluded: true,
    amenities: ["wifi", "desk", "heating", "kitchen", "terrace"],
    unavailable: [["2026-06-22", "2026-06-29"], ["2026-08-01", "2026-08-16"]]
  }
];

const addressLocations = {
  pedro: { lat: 41.65393, lng: -0.90783 },
  movera: { lat: 41.64929, lng: -0.82209 }
};

function whatsappLink(text) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;
}

// Spec line shared by the listing cards and the property page:
// "3 habitaciones · 1 baño · 70 m² · Planta 1" (only fields that exist)
function propertySpecs(property, translate, interpolateFn) {
  const specs = [];
  if (property.bedrooms != null) {
    specs.push(property.bedrooms === 1 ? translate("spec.bedroom") : interpolateFn("spec.bedrooms", { count: property.bedrooms }));
  }
  if (property.bathrooms != null) {
    specs.push(property.bathrooms === 1 ? translate("spec.bathroom") : interpolateFn("spec.bathrooms", { count: property.bathrooms }));
  }
  if (property.sizeM2 != null) specs.push(interpolateFn("spec.size", { size: property.sizeM2 }));
  if (property.floorNumber != null) {
    specs.push(property.floorNumber === 0 ? translate("spec.groundFloor") : interpolateFn("spec.floor", { floor: property.floorNumber }));
  }
  return specs;
}
